<?php
$data = $db->where('name', 'activate_code')->getOne(T_HTML_EMAILS);
$html = !empty($data->value) ? $data->value : '<p>Xin chào {{USERNAME}},</p><p>Mã kích hoạt tài khoản {{SITE_NAME}} của bạn là:</p><h1>{{CODE}}</h1>';
$replaces = array(
    'USERNAME' => $wo['user']['name'],
    'SITE_URL' => $wo['config']['site_url'],
    'EMAIL' => $wo['user']['email'],
    'CODE' => $wo['code'],
    'SITE_NAME' => $wo['config']['siteName'],
);
$html = Wo_ReplaceText($html, $replaces);
echo $html;
?>
