// Description: Lists WoWonder country IDs used by account settings forms.
export type CountryOption = {
  id: string;
  name: string;
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  { id: '1', name: 'United States' },
  { id: '2', name: 'Canada' },
  { id: '3', name: 'Afghanistan' },
  { id: '4', name: 'Albania' },
  { id: '5', name: 'Algeria' },
  { id: '6', name: 'American Samoa' },
  { id: '7', name: 'Andorra' },
  { id: '8', name: 'Angola' },
  { id: '9', name: 'Anguilla' },
  { id: '10', name: 'Antarctica' },
  { id: '11', name: 'Antigua and/or Barbuda' },
  { id: '12', name: 'Argentina' },
  { id: '13', name: 'Armenia' },
  { id: '14', name: 'Aruba' },
  { id: '15', name: 'Australia' },
  { id: '16', name: 'Austria' },
  { id: '17', name: 'Azerbaijan' },
  { id: '18', name: 'Bahamas' },
  { id: '19', name: 'Bahrain' },
  { id: '20', name: 'Bangladesh' },
  { id: '21', name: 'Barbados' },
  { id: '22', name: 'Belarus' },
  { id: '23', name: 'Belgium' },
  { id: '24', name: 'Belize' },
  { id: '25', name: 'Benin' },
  { id: '26', name: 'Bermuda' },
  { id: '27', name: 'Bhutan' },
  { id: '28', name: 'Bolivia' },
  { id: '29', name: 'Bosnia and Herzegovina' },
  { id: '30', name: 'Botswana' },
  { id: '31', name: 'Bouvet Island' },
  { id: '32', name: 'Brazil' },
  { id: '34', name: 'Brunei Darussalam' },
  { id: '35', name: 'Bulgaria' },
  { id: '36', name: 'Burkina Faso' },
  { id: '37', name: 'Burundi' },
  { id: '38', name: 'Cambodia' },
  { id: '39', name: 'Cameroon' },
  { id: '40', name: 'Cape Verde' },
  { id: '41', name: 'Cayman Islands' },
  { id: '42', name: 'Central African Republic' },
  { id: '43', name: 'Chad' },
  { id: '44', name: 'Chile' },
  { id: '45', name: 'China' },
  { id: '46', name: 'Christmas Island' },
  { id: '47', name: 'Cocos (Keeling) Islands' },
  { id: '48', name: 'Colombia' },
  { id: '49', name: 'Comoros' },
  { id: '50', name: 'Congo' },
  { id: '51', name: 'Cook Islands' },
  { id: '52', name: 'Costa Rica' },
  { id: '53', name: 'Croatia (Hrvatska)' },
  { id: '54', name: 'Cuba' },
  { id: '55', name: 'Cyprus' },
  { id: '56', name: 'Czech Republic' },
  { id: '57', name: 'Denmark' },
  { id: '58', name: 'Djibouti' },
  { id: '59', name: 'Dominica' },
  { id: '60', name: 'Dominican Republic' },
  { id: '61', name: 'East Timor' },
  { id: '62', name: 'Ecuador' },
  { id: '63', name: 'Egypt' },
  { id: '64', name: 'El Salvador' },
  { id: '65', name: 'Equatorial Guinea' },
  { id: '66', name: 'Eritrea' },
  { id: '67', name: 'Estonia' },
  { id: '68', name: 'Ethiopia' },
  { id: '69', name: 'Falkland Islands (Malvinas)' },
  { id: '70', name: 'Faroe Islands' },
  { id: '71', name: 'Fiji' },
  { id: '72', name: 'Finland' },
  { id: '73', name: 'France' },
  { id: '74', name: 'France, Metropolitan' },
  { id: '75', name: 'French Guiana' },
  { id: '76', name: 'French Polynesia' },
  { id: '77', name: 'French Southern Territories' },
  { id: '78', name: 'Gabon' },
  { id: '79', name: 'Gambia' },
  { id: '80', name: 'Georgia' },
  { id: '81', name: 'Germany' },
  { id: '82', name: 'Ghana' },
  { id: '83', name: 'Gibraltar' },
  { id: '84', name: 'Greece' },
  { id: '85', name: 'Greenland' },
  { id: '86', name: 'Grenada' },
  { id: '87', name: 'Guadeloupe' },
  { id: '88', name: 'Guam' },
  { id: '89', name: 'Guatemala' },
  { id: '90', name: 'Guinea' },
  { id: '91', name: 'Guinea-Bissau' },
  { id: '92', name: 'Guyana' },
  { id: '93', name: 'Haiti' },
  { id: '94', name: 'Heard and Mc Donald Islands' },
  { id: '95', name: 'Honduras' },
  { id: '96', name: 'Hong Kong' },
  { id: '97', name: 'Hungary' },
  { id: '98', name: 'Iceland' },
  { id: '99', name: 'India' },
  { id: '100', name: 'Indonesia' },
  { id: '101', name: 'Iran (Islamic Republic of)' },
  { id: '102', name: 'Iraq' },
  { id: '103', name: 'Ireland' },
  { id: '104', name: 'Israel' },
  { id: '105', name: 'Italy' },
  { id: '106', name: 'Ivory Coast' },
  { id: '107', name: 'Jamaica' },
  { id: '108', name: 'Japan' },
  { id: '109', name: 'Jordan' },
  { id: '110', name: 'Kazakhstan' },
  { id: '111', name: 'Kenya' },
  { id: '112', name: 'Kiribati' },
  { id: '113', name: "Korea, Democratic People's Republic of" },
  { id: '114', name: 'Korea, Republic of' },
  { id: '115', name: 'Kosovo' },
  { id: '116', name: 'Kuwait' },
  { id: '117', name: 'Kyrgyzstan' },
  { id: '118', name: "Lao People's Democratic Republic" },
  { id: '119', name: 'Latvia' },
  { id: '120', name: 'Lebanon' },
  { id: '121', name: 'Lesotho' },
  { id: '122', name: 'Liberia' },
  { id: '123', name: 'Libyan Arab Jamahiriya' },
  { id: '124', name: 'Liechtenstein' },
  { id: '125', name: 'Lithuania' },
  { id: '126', name: 'Luxembourg' },
  { id: '127', name: 'Macau' },
  { id: '128', name: 'Macedonia' },
  { id: '129', name: 'Madagascar' },
  { id: '130', name: 'Malawi' },
  { id: '131', name: 'Malaysia' },
  { id: '132', name: 'Maldives' },
  { id: '133', name: 'Mali' },
  { id: '134', name: 'Malta' },
  { id: '135', name: 'Marshall Islands' },
  { id: '136', name: 'Martinique' },
  { id: '137', name: 'Mauritania' },
  { id: '138', name: 'Mauritius' },
  { id: '139', name: 'Mayotte' },
  { id: '140', name: 'Mexico' },
  { id: '141', name: 'Micronesia, Federated States of' },
  { id: '142', name: 'Moldova, Republic of' },
  { id: '143', name: 'Monaco' },
  { id: '144', name: 'Mongolia' },
  { id: '145', name: 'Montenegro' },
  { id: '146', name: 'Montserrat' },
  { id: '147', name: 'Morocco' },
  { id: '148', name: 'Mozambique' },
  { id: '149', name: 'Myanmar' },
  { id: '150', name: 'Namibia' },
  { id: '151', name: 'Nauru' },
  { id: '152', name: 'Nepal' },
  { id: '153', name: 'Netherlands' },
  { id: '154', name: 'Netherlands Antilles' },
  { id: '155', name: 'New Caledonia' },
  { id: '156', name: 'New Zealand' },
  { id: '157', name: 'Nicaragua' },
  { id: '158', name: 'Niger' },
  { id: '159', name: 'Nigeria' },
  { id: '160', name: 'Niue' },
  { id: '161', name: 'Norfork Island' },
  { id: '162', name: 'Northern Mariana Islands' },
  { id: '163', name: 'Norway' },
  { id: '164', name: 'Oman' },
  { id: '165', name: 'Pakistan' },
  { id: '166', name: 'Palau' },
  { id: '167', name: 'Panama' },
  { id: '168', name: 'Papua New Guinea' },
  { id: '169', name: 'Paraguay' },
  { id: '170', name: 'Peru' },
  { id: '171', name: 'Philippines' },
  { id: '172', name: 'Pitcairn' },
  { id: '173', name: 'Poland' },
  { id: '174', name: 'Portugal' },
  { id: '175', name: 'Puerto Rico' },
  { id: '176', name: 'Qatar' },
  { id: '177', name: 'Reunion' },
  { id: '178', name: 'Romania' },
  { id: '179', name: 'Russian Federation' },
  { id: '180', name: 'Rwanda' },
  { id: '181', name: 'Saint Kitts and Nevis' },
  { id: '182', name: 'Saint Lucia' },
  { id: '183', name: 'Saint Vincent and the Grenadines' },
  { id: '184', name: 'Samoa' },
  { id: '185', name: 'San Marino' },
  { id: '186', name: 'Sao Tome and Principe' },
  { id: '187', name: 'Saudi Arabia' },
  { id: '188', name: 'Senegal' },
  { id: '189', name: 'Serbia' },
  { id: '190', name: 'Seychelles' },
  { id: '191', name: 'Sierra Leone' },
  { id: '192', name: 'Singapore' },
  { id: '193', name: 'Slovakia' },
  { id: '194', name: 'Slovenia' },
  { id: '195', name: 'Solomon Islands' },
  { id: '196', name: 'Somalia' },
  { id: '197', name: 'South Africa' },
  { id: '198', name: 'South Georgia South Sandwich Islands' },
  { id: '199', name: 'Spain' },
  { id: '200', name: 'Sri Lanka' },
  { id: '201', name: 'St. Helena' },
  { id: '202', name: 'St. Pierre and Miquelon' },
  { id: '203', name: 'Sudan' },
  { id: '204', name: 'Suriname' },
  { id: '205', name: 'Svalbarn and Jan Mayen Islands' },
  { id: '206', name: 'Swaziland' },
  { id: '207', name: 'Sweden' },
  { id: '208', name: 'Switzerland' },
  { id: '209', name: 'Syrian Arab Republic' },
  { id: '210', name: 'Taiwan' },
  { id: '211', name: 'Tajikistan' },
  { id: '212', name: 'Tanzania, United Republic of' },
  { id: '213', name: 'Thailand' },
  { id: '214', name: 'Togo' },
  { id: '215', name: 'Tokelau' },
  { id: '216', name: 'Tonga' },
  { id: '217', name: 'Trinidad and Tobago' },
  { id: '218', name: 'Tunisia' },
  { id: '219', name: 'Turkey' },
  { id: '220', name: 'Turkmenistan' },
  { id: '221', name: 'Turks and Caicos Islands' },
  { id: '222', name: 'Tuvalu' },
  { id: '223', name: 'Uganda' },
  { id: '224', name: 'Ukraine' },
  { id: '225', name: 'United Arab Emirates' },
  { id: '226', name: 'United Kingdom' },
  { id: '227', name: 'United States minor outlying islands' },
  { id: '228', name: 'Uruguay' },
  { id: '229', name: 'Uzbekistan' },
  { id: '230', name: 'Vanuatu' },
  { id: '231', name: 'Vatican City State' },
  { id: '232', name: 'Venezuela' },
  { id: '233', name: 'Vietnam' },
  { id: '238', name: 'Yemen' },
  { id: '239', name: 'Yugoslavia' },
  { id: '240', name: 'Zaire' },
  { id: '241', name: 'Zambia' },
  { id: '242', name: 'Zimbabwe' },
  { id: '243', name: 'Palestine' },
];
