import type {
  FeedPost,
  FeedTextPost,
  FeedVideoPost,
} from '../../domain/types/feed.types';
import { localPostEditsStorage } from '../../infrastructure/storage/localPostEditsStorage';

export type CaptionEditableFeedPost = FeedTextPost | FeedVideoPost;

export function isFeedPostCaptionEditable(
  post: FeedPost | null | undefined,
): post is CaptionEditableFeedPost {
  return post?.kind === 'text' || post?.kind === 'video';
}

export function getFeedPostCaption(post: FeedPost | null | undefined) {
  return isFeedPostCaptionEditable(post) ? post.caption ?? '' : '';
}

export function applyFeedPostCaptionEdit(
  post: FeedPost,
  text: string,
): FeedPost {
  if (!isFeedPostCaptionEditable(post)) return post;
  return {
    ...post,
    caption: text,
    // Mention ids are generated by the server mapper. The edit endpoint only
    // returns success, so keep rendering the freshly-entered plain text rather
    // than retaining stale mention metadata from the previous caption.
    mentionNames: undefined,
  };
}

export function applyLocalPostCaptionEdit<
  T extends { id: string; caption?: string; mentionNames?: string[] },
>(post: T): T {
  const localEdit = localPostEditsStorage.getCaptionEdit(post.id);
  return applyResolvedLocalPostCaptionEdit(post, localEdit);
}

function applyResolvedLocalPostCaptionEdit<
  T extends { id: string; caption?: string; mentionNames?: string[] },
>(
  post: T,
  localEdit: ReturnType<typeof localPostEditsStorage.getCaptionEdit>,
): T {
  if (!localEdit) return post;
  if (post.caption === localEdit.text && post.mentionNames === undefined) {
    return post;
  }
  return {
    ...post,
    caption: localEdit.text,
    mentionNames: undefined,
  };
}

export function applyLocalPostCaptionEdits<
  T extends { id: string; caption?: string; mentionNames?: string[] },
>(posts: T[], userId?: string): T[] {
  const localEdits = localPostEditsStorage.getCaptionEdits(userId);
  return posts.map(post =>
    applyResolvedLocalPostCaptionEdit(post, localEdits[post.id] ?? null),
  );
}
