<div class="container-fluid">
    <div>
        <h3>Cài đặt thông báo đẩy</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Cài đặt API</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Cài đặt thông báo đẩy</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt thông báo đẩy</h6>
                    <div class="alert alert-info">Hệ thống này cho phép tập lệnh của bạn gửi thông báo đẩy đến bất kỳ ứng dụng nào sử dụng API của chúng tôi.<br> Để bắt đầu, <a href="https://onesignal.com/" target="_blank">Đăng ký tại đây</a>.</div>
                    <div class="email-settings-alert"></div>
                    <form class="email-settings" method="POST">
                      
                      <div class="float-left">
                          <label for="push" class="main-label">Hệ thống thông báo đẩy</label>
                          <br><small class="admin-info">Bật tính năng này và người dùng sẽ nhận được thông báo trên trình duyệt/ứng dụng khi ứng dụng bị đóng.</small>
                      </div>
                      <div class="form-group float-right switcher">
                          <input type="hidden" name="push" value="0" />
                          <input type="checkbox" name="push" id="chck-push" value="1" <?php echo ($wo['config']['push'] == 1) ? 'checked': '';?>>
                          <label for="chck-push" class="check-trail"><span class="check-handler"></span></label>
                      </div>
                      <div class="clearfix"></div>
                      <hr>
                      
                      <div class="float-left">
                          <label for="android_push_messages" class="main-label">Tin nhắn đẩy Android </label>
                          <br><small class="admin-info">Bật tính năng này cho thiết bị Android. (Chỉ gửi tin nhắn đẩy của người dùng)</small>
                      </div>
                      <div class="form-group float-right switcher">
                          <input type="hidden" name="android_push_messages" value="0" />
                          <input type="checkbox" name="android_push_messages" id="chck-android_push_messages" value="1" <?php echo ($wo['config']['android_push_messages'] == 1) ? 'checked': '';?>>
                          <label for="chck-android_push_messages" class="check-trail"><span class="check-handler"></span></label>
                      </div>
                      <div class="clearfix"></div>
                      <hr>
                      
                      <div class="float-left">
                          <label for="ios_push_messages" class="main-label">Tin nhắn đẩy IOS (Tin nhắn đẩy của người dùng)</label>
                          <br><small class="admin-info">Bật tính năng này cho thiết bị IOS. (Chỉ gửi tin nhắn đẩy cho người dùng)</small>
                      </div>
                      <div class="form-group float-right switcher">
                          <input type="hidden" name="ios_push_messages" value="0" />
                          <input type="checkbox" name="ios_push_messages" id="chck-ios_push_messages" value="1" <?php echo ($wo['config']['ios_push_messages'] == 1) ? 'checked': '';?>>
                          <label for="chck-ios_push_messages" class="check-trail"><span class="check-handler"></span></label>
                      </div>
                      <div class="clearfix"></div>
                      <hr>
                      
                      <div class="float-left">
                          <label for="android_push_native" class="main-label">Thông báo trang web gốc của Android Push</label>
                          <br><small class="admin-info">Bật tính năng này cho thiết bị Android. (Thích, Theo dõi, Thắc mắc, Bình luận, v.v.)</small>
                      </div>
                      <div class="form-group float-right switcher">
                          <input type="hidden" name="android_push_native" value="0" />
                          <input type="checkbox" name="android_push_native" id="chck-android_push_native" value="1" <?php echo ($wo['config']['android_push_native'] == 1) ? 'checked': '';?>>
                          <label for="chck-android_push_native" class="check-trail"><span class="check-handler"></span></label>
                      </div>
                      <div class="clearfix"></div>
                      <hr>
                      
                      <div class="float-left">
                          <label for="ios_push_native" class="main-label">Thông báo trang web gốc của iOS Push </label>
                          <br><small class="admin-info">Kích hoạt tính năng này cho các thiết bị IOS (Thích, Theo dõi, Thắc mắc, Bình luận, v.v.)</small>
                      </div>
                      <div class="form-group float-right switcher">
                          <input type="hidden" name="ios_push_native" value="0" />
                          <input type="checkbox" name="ios_push_native" id="chck-ios_push_native" value="1" <?php echo ($wo['config']['ios_push_native'] == 1) ? 'checked': '';?>>
                          <label for="chck-ios_push_native" class="check-trail"><span class="check-handler"></span></label>
                      </div>
                      <div class="clearfix"></div>
                      <hr>
                      
                      <div class="float-left">
                          <label for="web_push" class="main-label">Thông báo đẩy trên web</label>
                          <br><small class="admin-info">Người dùng sẽ được thông báo trên trình duyệt web (Chrome, Firefox, v.v.). Yêu cầu SSL</small>
                      </div>
                      <div class="form-group float-right switcher">
                          <input type="hidden" name="web_push" value="0" />
                          <input type="checkbox" name="web_push" id="chck-web_push" value="1" <?php echo ($wo['config']['web_push'] == 1) ? 'checked': '';?>>
                          <label for="chck-web_push" class="check-trail"><span class="check-handler"></span></label>
                      </div>
                      <div class="clearfix"></div>
                      <hr>

                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
						<div><span class="help-block">Cần trợ giúp? <a href="https://documentation.onesignal.com/v3.0/docs/setup" target="_blank">Đọc Tài liệu</a></span></div>
                    </form>
                </div>
            </div>
			
        </div>

        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt thông báo toàn cầu của Android (Thích, Không thích, Bình luận, Theo dõi, v.v.)</h6>
                    <div class="email2-settings-alert"></div>
                    <form class="email2-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID ứng dụng OneSignal</label>
                                <input type="text" id="android_n_push_id" name="android_n_push_id" class="form-control" value="<?php echo $wo['config']['android_n_push_id'];?>">
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa API REST</label>
                                <input type="text" id="android_n_push_key" name="android_n_push_key" class="form-control" value="<?php echo $wo['config']['android_n_push_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt thông báo toàn cầu của iOS (Thích, Không thích, Bình luận, Theo dõi, v.v.)</h6>
                    <div class="email2-settings-alert"></div>
                    <form class="email2-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID ứng dụng OneSignal</label>
                                <input type="text" id="ios_n_push_id" name="ios_n_push_id" class="form-control" value="<?php echo $wo['config']['ios_n_push_id'];?>">
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa API REST</label>
                                <input type="text" id="ios_n_push_key" name="ios_n_push_key" class="form-control" value="<?php echo $wo['config']['ios_n_push_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt thông báo toàn cầu trên web (Thích, Không thích, Bình luận, Theo dõi, v.v.)</h6>
                    <div class="email2-settings-alert"></div>
                    <form class="email2-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID ứng dụng OneSignal</label>
                                <input type="text" id="web_push_id" name="web_push_id" class="form-control" value="<?php echo $wo['config']['web_push_id'];?>">
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa API REST</label>
                                <input type="text" id="web_push_key" name="web_push_key" class="form-control" value="<?php echo $wo['config']['web_push_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Thông báo Android & Chat Cài đặt thông báo đẩy</h6>
                    <div class="email3-settings-alert"></div>
                    <form class="email3-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID ứng dụng OneSignal</label>
                                <input type="text" id="android_m_push_id" name="android_m_push_id" class="form-control" value="<?php echo $wo['config']['android_m_push_id'];?>">
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa API REST</label>
                                <input type="text" id="android_m_push_key" name="android_m_push_key" class="form-control" value="<?php echo $wo['config']['android_m_push_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">iOS Messenger & Chat Cài đặt thông báo</h6>
                    <div class="ios-m-settings-alert"></div>
                    <form class="ios-m-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID ứng dụng OneSignal</label>
                                <input type="text" id="ios_m_push_id" name="ios_m_push_id" class="form-control" value="<?php echo $wo['config']['ios_m_push_id'];?>">
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa API REST</label>
                                <input type="text" id="ios_m_push_key" name="ios_m_push_key" class="form-control" value="<?php echo $wo['config']['ios_m_push_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>

        
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        if (configName == 'redis') { 
            setToTrue = 'N';
            if ($(this).is(":checked") === true) {
              setToTrue = 'Y';
            }
        }
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number]').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});
</script>