// Description: Defines app route names shared by navigation screens.
export const ROUTES = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  MAIN_TABS: 'MainTabs',
  FEED: 'Feed',
  EXPLORE: 'Explore',
  REELS: 'Reels',
  NOTIFICATIONS: 'Notifications',
  PROFILE: 'Profile',
  MY_PHOTOS: 'MyPhotos',
  ALBUMS: 'Albums',
  CREATE_ALBUM: 'CreateAlbum',
  MY_VIDEOS: 'MyVideos',
  MESSAGES: 'Messages',
  CALLS: 'Calls',
  SEARCH: 'Search',
  SEARCH_FILTER: 'SearchFilter',
  SAVED_POSTS: 'SavedPosts',
  SEARCH_EMPTY: 'SearchEmpty',
  CREATE_PAGE: 'CreatePage',
  CREATE_PRODUCT: 'CreateProduct',
  CREATE_EVENT: 'CreateEvent',
  CREATE_GROUP: 'CreateGroup',
  EXPLORE_GROUPS: 'ExploreGroups',
  GROUP_DETAIL: 'GroupDetail',
  EVENTS: 'Events',
  FUNDING: 'Funding',
  FOLLOWING: 'Following',
  BOOSTED: 'Boosted',
  BLOGS: 'Blogs',
  BLOG_FILTER_CATEGORY: 'BlogFilterCategory',
  BLOG_DETAIL: 'BlogDetail',
  MOVIES: 'Movies',
  JOBS: 'Jobs',
  JOB_DETAIL: 'JobDetail',
  SETTINGS: 'Settings',
  EARNINGS: 'Earnings',
  AFFILIATES: 'Affiliates',
  INVITE_FRIENDS: 'InviteFriends',
  MY_POINTS: 'MyPoints',
  WITHDRAWAL: 'Withdrawal',
} as const;

export type RouteName = (typeof ROUTES)[keyof typeof ROUTES];
