<?php
$calling_user = (!empty($wo['calling_user']) && is_array($wo['calling_user'])) ? $wo['calling_user'] : array();
$calling_user_avatar = !empty($calling_user['avatar']) ? $calling_user['avatar'] : '';
$calling_user_name = !empty($calling_user['name']) ? $calling_user['name'] : '';
$lang_calling = !empty($wo['lang']['calling']) ? $wo['lang']['calling'] : 'Calling';
$lang_calling_desc = !empty($wo['lang']['calling_desc']) ? $wo['lang']['calling_desc'] : '';
$lang_cancel = !empty($wo['lang']['cancel']) ? $wo['lang']['cancel'] : 'Cancel';
?>
<div class="modal fade" id="calling-modal" role="dialog" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog wow_mat_mdl modal-sm">
		<div class="modal-content text-center wo_calling_modals">
			<img src="<?php echo $calling_user_avatar; ?>">
			<div class="modal-header">
				<div class="avatar">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M6.62,10.79C8.06,13.62 10.38,15.94 13.21,17.38L15.41,15.18C15.69,14.9 16.08,14.82 16.43,14.93C17.55,15.3 18.75,15.5 20,15.5A1,1 0 0,1 21,16.5V20A1,1 0 0,1 20,21A17,17 0 0,1 3,4A1,1 0 0,1 4,3H7.5A1,1 0 0,1 8.5,4C8.5,5.25 8.7,6.45 9.07,7.57C9.18,7.92 9.1,8.31 8.82,8.59L6.62,10.79Z" /></svg>
					<img width="100" height="100" src="<?php echo $calling_user_avatar; ?>">
				</div>
				<h4 class="modal-title"><?php echo $lang_calling; ?> <?php echo $calling_user_name; ?> ..</h4>
			</div>
			<div class="modal-body">
				<p><?php echo $lang_calling_desc; ?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-mat cancel-call" onclick="Wo_CancelCall();"><i class="fa fa-times progress-icon" data-icon="times"></i> <?php echo $lang_cancel; ?></button>
			</div>
		</div>
	</div>
</div>