<?php
$wo['config']['ffmpeg']  = is_executable($wo['config']['ffmpeg_binary_file']);
function isEnabled($func) {
    return is_callable($func) && false === stripos(ini_get('disable_functions'), $func);
}
$enabled = true;
if (!isEnabled('shell_exec')) {
    $enabled = false;
}
?>
<div class="container-fluid">
    <div>
        <h3>Cấu hình tải tệp lên</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Cài đặt</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Cấu hình tải tệp lên</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <?php if ($wo['config']['website_mode'] != 'facebook') { ?>
        <div class="alert alert-warning">Lưu ý: Một số tính năng bị vô hiệu hóa do chế độ trang web bạn sử dụng.</div>
    <?php } ?>
    <div class="row">
        <div class="col-lg-6 col-md-6 ">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình tải lên và chia sẻ tệp</h6>
                    <div class="upload-settings-alert"></div>
                    <form class="upload-settings" method="POST">
                        <div class="float-left">
                            <label for="fileSharing" class="main-label">Tải lên và chia sẻ tệp</label>
                            <br><small class="admin-info">Bằng cách bật tính năng này, người dùng có thể chia sẻ và tải tệp lên trang web của bạn.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="fileSharing" value="0" />
                            <input type="checkbox" name="fileSharing" id="chck-fileSharing" value="1" <?php echo ($wo['config']['fileSharing'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('fileSharing')) ?>>
                            <label for="chck-fileSharing" class="check-trail <?php echo(EnableForMode('fileSharing',true)) ?>" <?php echo(EnableForMode('fileSharing',false,true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="float-left">
                            <label for="video_upload" class="main-label">Tải lên và chia sẻ video</label>
							<div class="dropdown user_filter_drop">
								<button class="btn btn-light" data-toggle="dropdown">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8 13C6.14 13 4.59 14.28 4.14 16H2V18H4.14C4.59 19.72 6.14 21 8 21S11.41 19.72 11.86 18H22V16H11.86C11.41 14.28 9.86 13 8 13M8 19C6.9 19 6 18.1 6 17C6 15.9 6.9 15 8 15S10 15.9 10 17C10 18.1 9.1 19 8 19M19.86 6C19.41 4.28 17.86 3 16 3S12.59 4.28 12.14 6H2V8H12.14C12.59 9.72 14.14 11 16 11S19.41 9.72 19.86 8H22V6H19.86M16 9C14.9 9 14 8.1 14 7C14 5.9 14.9 5 16 5S18 5.9 18 7C18 8.1 17.1 9 16 9Z"></path></svg>
								</button>
								<ul class="dropdown-menu">
									<div class="dropdown-menu-innr">
										<b>Ai có thể sử dụng tính năng này?</b>
										<div>
											<div class="round_check">
												<input type="radio" name="video_upload_request" id="video_upload_request-admin" onchange="SelectProModel('can_use_video_upload',this)" value="admin" <?php echo ($wo['config']['video_upload_request'] == 'admin')   ? ' checked' : '';?>>
												<label class="radio-inline" for="video_upload_request-admin" data-toggle="tooltip" data-placement="bottom" title="Admin"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,1L3,5V11C3,16.55 6.84,21.74 12,23C17.16,21.74 21,16.55 21,11V5L12,1M12,5A3,3 0 0,1 15,8A3,3 0 0,1 12,11A3,3 0 0,1 9,8A3,3 0 0,1 12,5M17.13,17C15.92,18.85 14.11,20.24 12,20.92C9.89,20.24 8.08,18.85 6.87,17C6.53,16.5 6.24,16 6,15.47C6,13.82 8.71,12.47 12,12.47C15.29,12.47 18,13.79 18,15.47C17.76,16 17.47,16.5 17.13,17Z"></path></svg></label> 
											</div>
											<div class="round_check">
												<input type="radio" name="video_upload_request" id="video_upload_request-all" onchange="SelectProModel('can_use_video_upload',this)" value="all" <?php echo ($wo['config']['video_upload_request'] == 'all')   ? ' checked' : '';?>>
												<label class="radio-inline" for="video_upload_request-all" data-toggle="tooltip" data-placement="bottom" title="All Users"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z"></path></svg></label> 
											</div>
											<div class="round_check">
												<input type="radio" name="video_upload_request" id="video_upload_request-verified" onchange="SelectProModel('can_use_video_upload',this)" value="verified" <?php echo ($wo['config']['video_upload_request'] == 'verified')   ? ' checked' : '';?>>
												<label class="radio-inline" for="video_upload_request-verified" data-toggle="tooltip" data-placement="bottom" title="Verified Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21.1,12.5L22.5,13.91L15.97,20.5L12.5,17L13.9,15.59L15.97,17.67L21.1,12.5M10,17L13,20H3V18C3,15.79 6.58,14 11,14L12.89,14.11L10,17M11,4A4,4 0 0,1 15,8A4,4 0 0,1 11,12A4,4 0 0,1 7,8A4,4 0 0,1 11,4Z"></path></svg></label> 
											</div>
											<div class="round_check">
												<input type="radio" name="video_upload_request" id="video_upload_request-pro" onchange="SelectProModel('can_use_video_upload',this)" value="pro" <?php echo ($wo['config']['video_upload_request'] == 'pro')   ? ' checked' : '';?>>
												<label class="radio-inline" for="video_upload_request-pro" data-toggle="tooltip" data-placement="bottom" title="Pro Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12M5,13.28L7.45,14.77L6.8,11.96L9,10.08L6.11,9.83L5,7.19L3.87,9.83L1,10.08L3.18,11.96L2.5,14.77L5,13.28Z"></path></svg></label> 
											</div>
										</div>
									</div>
								</ul>
							</div>
                            <br><small class="admin-info">Bật khả năng cho phép người dùng chia sẻ và tải lên video. <br>Bạn có thể cấu hình cài đặt trình chuyển đổi video từ Cài đặt FFMPEG bên dưới.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="video_upload" value="0" />
                            <input type="checkbox" name="video_upload" id="chck-video_upload" value="1" <?php echo ($wo['config']['video_upload'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('video_upload')) ?>>
                            <label for="chck-video_upload" class="check-trail <?php echo(EnableForMode('video_upload',true)) ?>" <?php echo(EnableForMode('video_upload',false,true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="float-left">
                            <label for="video_upload" class="main-label">Tải lên Reels</label>
                            <div class="dropdown user_filter_drop">
                                <button class="btn btn-light" data-toggle="dropdown">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8 13C6.14 13 4.59 14.28 4.14 16H2V18H4.14C4.59 19.72 6.14 21 8 21S11.41 19.72 11.86 18H22V16H11.86C11.41 14.28 9.86 13 8 13M8 19C6.9 19 6 18.1 6 17C6 15.9 6.9 15 8 15S10 15.9 10 17C10 18.1 9.1 19 8 19M19.86 6C19.41 4.28 17.86 3 16 3S12.59 4.28 12.14 6H2V8H12.14C12.59 9.72 14.14 11 16 11S19.41 9.72 19.86 8H22V6H19.86M16 9C14.9 9 14 8.1 14 7C14 5.9 14.9 5 16 5S18 5.9 18 7C18 8.1 17.1 9 16 9Z"></path></svg>
                                </button>
                                <ul class="dropdown-menu">
                                    <div class="dropdown-menu-innr">
                                        <b>Ai có thể sử dụng tính năng này?</b>
                                        <div>
                                            <div class="round_check">
                                                <input type="radio" name="reels_upload_request" id="reels_upload_request-admin" onchange="SelectProModel('can_use_reels_upload',this)" value="admin" <?php echo ($wo['config']['reels_upload_request'] == 'admin')   ? ' checked' : '';?>>
                                                <label class="radio-inline" for="reels_upload_request-admin" data-toggle="tooltip" data-placement="bottom" title="Admin"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,1L3,5V11C3,16.55 6.84,21.74 12,23C17.16,21.74 21,16.55 21,11V5L12,1M12,5A3,3 0 0,1 15,8A3,3 0 0,1 12,11A3,3 0 0,1 9,8A3,3 0 0,1 12,5M17.13,17C15.92,18.85 14.11,20.24 12,20.92C9.89,20.24 8.08,18.85 6.87,17C6.53,16.5 6.24,16 6,15.47C6,13.82 8.71,12.47 12,12.47C15.29,12.47 18,13.79 18,15.47C17.76,16 17.47,16.5 17.13,17Z"></path></svg></label>
                                            </div>
                                            <div class="round_check">
                                                <input type="radio" name="reels_upload_request" id="reels_upload_request-all" onchange="SelectProModel('can_use_reels_upload',this)" value="all" <?php echo ($wo['config']['reels_upload_request'] == 'all')   ? ' checked' : '';?>>
                                                <label class="radio-inline" for="reels_upload_request-all" data-toggle="tooltip" data-placement="bottom" title="All Users"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z"></path></svg></label>
                                            </div>
                                            <div class="round_check">
                                                <input type="radio" name="reels_upload_request" id="reels_upload_request-verified" onchange="SelectProModel('can_use_reels_upload',this)" value="verified" <?php echo ($wo['config']['reels_upload_request'] == 'verified')   ? ' checked' : '';?>>
                                                <label class="radio-inline" for="reels_upload_request-verified" data-toggle="tooltip" data-placement="bottom" title="Verified Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21.1,12.5L22.5,13.91L15.97,20.5L12.5,17L13.9,15.59L15.97,17.67L21.1,12.5M10,17L13,20H3V18C3,15.79 6.58,14 11,14L12.89,14.11L10,17M11,4A4,4 0 0,1 15,8A4,4 0 0,1 11,12A4,4 0 0,1 7,8A4,4 0 0,1 11,4Z"></path></svg></label>
                                            </div>
                                            <div class="round_check">
                                                <input type="radio" name="reels_upload_request" id="reels_upload_request-pro" onchange="SelectProModel('can_use_reels_upload',this)" value="pro" <?php echo ($wo['config']['reels_upload_request'] == 'pro')   ? ' checked' : '';?>>
                                                <label class="radio-inline" for="reels_upload_request-pro" data-toggle="tooltip" data-placement="bottom" title="Pro Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12M5,13.28L7.45,14.77L6.8,11.96L9,10.08L6.11,9.83L5,7.19L3.87,9.83L1,10.08L3.18,11.96L2.5,14.77L5,13.28Z"></path></svg></label>
                                            </div>
                                        </div>
                                    </div>
                                </ul>
                            </div>
                            <br><small class="admin-info">Bật khả năng cho phép người dùng chia sẻ và tải lên các cuộn phim. <br>Bạn có thể cấu hình cài đặt trình chuyển đổi video từ Cài đặt FFMPEG bên dưới.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="reels_upload" value="0" />
                            <input type="checkbox" name="reels_upload" id="chck-reels_upload" value="1" <?php echo ($wo['config']['reels_upload'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('reels_upload')) ?>>
                            <label for="chck-reels_upload" class="check-trail <?php echo(EnableForMode('reels_upload',true)) ?>" <?php echo(EnableForMode('reels_upload',false,true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="float-left">
                            <label for="audio_upload" class="main-label">Tải lên và chia sẻ âm thanh</label>
							<div class="dropdown user_filter_drop">
								<button class="btn btn-light" data-toggle="dropdown">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8 13C6.14 13 4.59 14.28 4.14 16H2V18H4.14C4.59 19.72 6.14 21 8 21S11.41 19.72 11.86 18H22V16H11.86C11.41 14.28 9.86 13 8 13M8 19C6.9 19 6 18.1 6 17C6 15.9 6.9 15 8 15S10 15.9 10 17C10 18.1 9.1 19 8 19M19.86 6C19.41 4.28 17.86 3 16 3S12.59 4.28 12.14 6H2V8H12.14C12.59 9.72 14.14 11 16 11S19.41 9.72 19.86 8H22V6H19.86M16 9C14.9 9 14 8.1 14 7C14 5.9 14.9 5 16 5S18 5.9 18 7C18 8.1 17.1 9 16 9Z"></path></svg>
								</button>
								<ul class="dropdown-menu">
									<div class="dropdown-menu-innr">
										<b>Ai có thể sử dụng tính năng này?</b>
										<div>
											<div class="round_check">
												<input type="radio" name="audio_upload_request" id="audio_upload_request-admin" onchange="SelectProModel('can_use_audio_upload',this)" value="admin" <?php echo ($wo['config']['audio_upload_request'] == 'admin')   ? ' checked' : '';?>>
												<label class="radio-inline" for="audio_upload_request-admin" data-toggle="tooltip" data-placement="bottom" title="Admin"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,1L3,5V11C3,16.55 6.84,21.74 12,23C17.16,21.74 21,16.55 21,11V5L12,1M12,5A3,3 0 0,1 15,8A3,3 0 0,1 12,11A3,3 0 0,1 9,8A3,3 0 0,1 12,5M17.13,17C15.92,18.85 14.11,20.24 12,20.92C9.89,20.24 8.08,18.85 6.87,17C6.53,16.5 6.24,16 6,15.47C6,13.82 8.71,12.47 12,12.47C15.29,12.47 18,13.79 18,15.47C17.76,16 17.47,16.5 17.13,17Z"></path></svg></label> 
											</div>
											<div class="round_check">
												<input type="radio" name="audio_upload_request" id="audio_upload_request-all" onchange="SelectProModel('can_use_audio_upload',this)" value="all" <?php echo ($wo['config']['audio_upload_request'] == 'all')   ? ' checked' : '';?>>
												<label class="radio-inline" for="audio_upload_request-all" data-toggle="tooltip" data-placement="bottom" title="All Users"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z"></path></svg></label> 
											</div>
											<div class="round_check">
												<input type="radio" name="audio_upload_request" id="audio_upload_request-verified" onchange="SelectProModel('can_use_audio_upload',this)" value="verified" <?php echo ($wo['config']['audio_upload_request'] == 'verified')   ? ' checked' : '';?>>
												<label class="radio-inline" for="audio_upload_request-verified" data-toggle="tooltip" data-placement="bottom" title="Verified Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21.1,12.5L22.5,13.91L15.97,20.5L12.5,17L13.9,15.59L15.97,17.67L21.1,12.5M10,17L13,20H3V18C3,15.79 6.58,14 11,14L12.89,14.11L10,17M11,4A4,4 0 0,1 15,8A4,4 0 0,1 11,12A4,4 0 0,1 7,8A4,4 0 0,1 11,4Z"></path></svg></label> 
											</div>
											<div class="round_check">
												<input type="radio" name="audio_upload_request" id="audio_upload_request-pro" onchange="SelectProModel('can_use_audio_upload',this)" value="pro" <?php echo ($wo['config']['audio_upload_request'] == 'pro')   ? ' checked' : '';?>>
												<label class="radio-inline" for="audio_upload_request-pro" data-toggle="tooltip" data-placement="bottom" title="Pro Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12M5,13.28L7.45,14.77L6.8,11.96L9,10.08L6.11,9.83L5,7.19L3.87,9.83L1,10.08L3.18,11.96L2.5,14.77L5,13.28Z"></path></svg></label> 
											</div>
										</div>
									</div>
								</ul>
							</div>
                            <br><small class="admin-info">Bật khả năng cho phép người dùng chia sẻ và tải lên các tệp nhạc và âm thanh.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="audio_upload" value="0" />
                            <input type="checkbox" name="audio_upload" id="chck-audio_upload" value="1" <?php echo ($wo['config']['audio_upload'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('audio_upload')) ?>>
                            <label for="chck-audio_upload" class="check-trail <?php echo(EnableForMode('audio_upload',true)) ?>" <?php echo(EnableForMode('audio_upload',false,true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="float-left">
                            <label for="css_upload" class="main-label">Tải lên & Sửa đổi CSS</label>
                            <br><small class="admin-info">Cho phép người dùng tải lên tệp CSS của riêng họ để thiết kế hồ sơ.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="css_upload" value="0" />
                            <input type="checkbox" name="css_upload" id="chck-css_upload" value="1" <?php echo ($wo['config']['css_upload'] == 1) ? 'checked': '';?> <?php echo(EnableForMode('css_upload')) ?>>
                            <label for="chck-css_upload" class="check-trail <?php echo(EnableForMode('css_upload',true)) ?>" <?php echo(EnableForMode('css_upload',false,true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->

                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 ">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Giới hạn tải lên và tệp</h6>
                    <div class="alert alert-warning"><i class="fa fa-fw fa-exclamation-triangle"></i> <strong>Quan trọng:</strong> Hãy đảm bảo rằng bạn không cho phép các tệp PHP, JS, HTML, XML, XPHP, PHP5, nếu bạn làm vậy, trang web của bạn có thể gặp rủi ro.</div>
                    <form class="upload-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tiện ích mở rộng được phép</label>
                                <input type="text" id="allowedExtenstion" name="allowedExtenstion" class="form-control" value="<?php echo $wo['config']['allowedExtenstion']?>">
                                <small class="admin-info">Chỉ những loại tệp đó người dùng mới có thể tải lên trang web của bạn. (phân cách bằng dấu phẩy,)</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Các loại MIME được phép</label>
                                <input type="text" id="mime_types" name="mime_types" class="form-control" value="<?php echo $wo['config']['mime_types']?>">
                                <small class="admin-info">Chỉ những tệp loại MIME mà người dùng có thể tải lên trang web của bạn. (phân tách bằng dấu phẩy,)</small>
                            </div>
                        </div>
                        <label class="form-check-label" for="maxUpload">Kích thước tải lên tối đa</label>
                        <select class="form-control show-tick" id="maxUpload" name="maxUpload">
                              <option value="2000000"    <?php echo ($wo['config']['maxUpload'] == 2000000)   ? ' selected': '';?>>2 MB</option>
                              <option value="6000000"    <?php echo ($wo['config']['maxUpload'] == 6000000)   ? ' selected': '';?>>6 MB</option>
                              <option value="12000000"   <?php echo ($wo['config']['maxUpload'] == 12000000)  ? ' selected': '';?>>12 MB</option>
                              <option value="24000000"   <?php echo ($wo['config']['maxUpload'] == 24000000)  ? ' selected': '';?>>24 MB</option>
                              <option value="48000000"   <?php echo ($wo['config']['maxUpload'] == 48000000)  ? ' selected': '';?>>48 MB</option>
                              <option value="96000000"   <?php echo ($wo['config']['maxUpload'] == 96000000)  ? ' selected': '';?>>96 MB</option>
                              <option value="256000000"  <?php echo ($wo['config']['maxUpload'] == 256000000) ? ' selected': '';?>>256 MB</option>
                              <option value="512000000"  <?php echo ($wo['config']['maxUpload'] == 512000000) ? ' selected': '';?>>512 MB</option>
                              <option value="1000000000" <?php echo ($wo['config']['maxUpload'] == 1000000000) ? ' selected': '';?>>1 GB</option>
                              <option value="5000000000" <?php echo ($wo['config']['maxUpload'] == 5000000000) ? ' selected': '';?>>5 GB</option>
                              <option value="10000000000" <?php echo ($wo['config']['maxUpload'] == 10000000000) ? ' selected': '';?>>10 GB</option>
                        </select>
                        <small class="admin-info">Đặt kích thước tải lên tối đa mà người dùng có thể sử dụng để tải lên tệp, video, nhạc và hình ảnh.</small>
                        <div class="clearfix"></div>
                        <label class="form-check-label" for="images_quality">Mức độ nén hình ảnh</label>
                        <select class="form-control show-tick" id="images_quality" name="images_quality">
                              <option value="99" <?php echo ($wo['config']['images_quality'] == 99)   ? ' selected': '';?>>Rất thấp</option>                      
                              <option value="90" <?php echo ($wo['config']['images_quality'] == 90)   ? ' selected': '';?>>Thấp</option>
                              <option value="60" <?php echo ($wo['config']['images_quality'] == 60)   ? ' selected': '';?>>Trung Bình</option>
                              <option value="20" <?php echo ($wo['config']['images_quality'] == 20)   ? ' selected': '';?>>Cao</option>
                              <option value="20" <?php echo ($wo['config']['images_quality'] == 10)   ? ' selected': '';?>>Rất cao</option>
                        </select>
                        <small class="admin-info">Thiết lập mức độ nén hình ảnh, mức càng cao thì chất lượng hình ảnh càng thấp.</small>
                        <div class="clearfix"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12">
            <h3>Cài đặt trình chuyển đổi video FFMPEG<hr></h3>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình FFMPEG</h6>

                    <form class="ffmpeg-settings" method="POST">
                        <div class="float-left">
                            <label for="ffmpeg_system" class="main-label">Hệ thống FFMPEG</label>
                            <br><small class="admin-info">Hệ thống này sẽ nén, chuyển đổi và tối ưu hóa video sang định dạng mp4. <br>Hệ thống này yêu cầu "ffmpeg" phải được cài đặt trên máy chủ của bạn.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="ffmpeg_system" value="0" />
                            <input type="checkbox" name="ffmpeg_system" id="chck-ffmpeg_system" value="1" <?php echo ($wo['config']['ffmpeg_system'] == 'on') ? 'checked': '';?>>
                            <label for="chck-ffmpeg_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <?php if ($enabled == false): ?>
                            <div class="alert alert-danger">
                               shell_exec() đã bị vô hiệu hóa vì lý do bảo mật, vui lòng liên hệ với nhà cung cấp dịch vụ lưu trữ của bạn để bật nó. shell_exec là bắt buộc để bật hệ thống này.
                            </div>
                        <?php endif; ?>
                        <hr>
                        <div class="form-group  form-float">
                            <div class="form-line">
                                <?php if (!$wo['config']['ffmpeg']): ?>
                                <div class="alert alert-danger">Tệp nhị phân FFmpeg không tồn tại trên đường dẫn: <?php echo $wo['config']['ffmpeg_binary_file'] ?></div>
                                <?php else: ?>
                                <label class="form-label ">Đường dẫn tệp nhị phân FFMPEG</label>
                                <?php endif; ?>
                                <input type="text" id="ffmpeg_binary_file" name="ffmpeg_binary_file" class="form-control" value="<?php echo $wo['config']['ffmpeg_binary_file'] ?>">
                                <small class="admin-info">Ví dụ: Linux(/usr/bin/ffmpeg) hoặc Windows(C:\\ffmpeg\bin\ffmpeg.exe)</small>
                            </div>
                        </div>

                        <?php if ($wo['config']['ffmpeg'] && $enabled == true): ?>
                            <hr>
                        <label for="comments_default_num" class="">Chuyển đổi tốc độ video</label>
                        <select class="form-control show-tick" id="convert_speed" name="convert_speed">
                            <option value="ultrafast" <?php echo ($wo['config']['convert_speed'] == 'ultrafast') ? 'selected': '';?>>Cực nhanh</option>
                            <option value="superfast" <?php echo ($wo['config']['convert_speed'] == 'superfast') ? 'selected': '';?>>Siêu nhanh</option>
                            <option value="veryfast" <?php echo ($wo['config']['convert_speed'] == 'veryfast') ? 'selected': '';?>>Rất nhanh</option>
                            <option value="faster" <?php echo ($wo['config']['convert_speed'] == 'faster') ? 'selected': '';?>>Nhanh hơn</option>
                            <option value="fast" <?php echo ($wo['config']['convert_speed'] == 'fast') ? 'selected': '';?>>Nhanh</option>
                            <option value="medium" <?php echo ($wo['config']['convert_speed'] == 'medium') ? 'selected': '';?>>Trung bình</option>
                            <option value="slow" <?php echo ($wo['config']['convert_speed'] == 'slow') ? 'selected': '';?>>Chậm</option>
                            <option value="slower" <?php echo ($wo['config']['convert_speed'] == 'slower') ? 'selected': '';?>>Chậm hơn</option>
                            <option value="veryslow" <?php echo ($wo['config']['convert_speed'] == 'veryslow') ? 'selected': '';?>>Rất chậm</option>
                        </select>
                        <small class="admin-info">Điều này ảnh hưởng đến tốc độ mã hóa. Sử dụng cài đặt trước chậm hơn sẽ mang lại khả năng nén tốt hơn hoặc chất lượng trên mỗi kích thước tệp, trong khi cài đặt trước nhanh hơn sẽ mang lại khả năng nén kém hơn và kích thước tệp lớn hơn.</small><?php endif; ?>

                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label ">Tiện ích mở rộng được phép</label>
                                <input type="text" id="allowedffmpegExtenstion" name="allowedffmpegExtenstion" class="form-control" value="<?php echo $wo['config']['allowedffmpegExtenstion']?>">
                                <small class="admin-info">Chỉ những loại video đó người dùng mới có thể tải lên trang web của bạn. (phân cách bằng dấu phẩy,)</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label ">Các loại MIME được phép</label>
                                <input type="text" id="ffmpeg_mime_types" name="ffmpeg_mime_types" class="form-control" value="<?php echo $wo['config']['ffmpeg_mime_types']?>">
                                <small class="admin-info">Chỉ những video loại MIME mà người dùng có thể tải lên trang web của bạn. (phân cách bằng dấu phẩy,)</small>
                            </div>
                        </div>
                        <hr>
                        <div class="alert alert-info">
                           <i class="fa fa-fw fa-exclamation-triangle"></i> <strong>Thông tin: </strong> Để biết thêm thông tin về cách thiết lập FFMPEG, vui lòng truy cập <a href="https://docs.hisotechgroup.com/#idocs_ffmpeg" target="_blank">Tài liệu</a> trang.

                       </div>
                       <div class="alert alert-warning">
                          Hãy đảm bảo gỡ lỗi FFMPEG bên dưới sau khi cấu hình ffmpeg.
                      </div>
                        <div class="ffmpeg-settings-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
             <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Gỡ lỗi FFMPEG</h6>
                    <div class="alert alert-info">Tính năng này sẽ kiểm tra Cấu hình FFMPEG và đảm bảo hệ thống hoạt động tốt.</div>
                    <form class="debug-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Nhật ký gỡ lỗi</label>
                                <textarea name="debug_ffmpeg" id="debug_ffmpeg" class="form-control" cols="30" rows="5" style="height: 700px !important;" disabled>Nhấp vào Gỡ lỗi FFMPEG để hiển thị kết quả kiểm tra.</textarea>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="debug-settings-alert"></div>
                        <button type="submit" class="btn btn-success m-t-15 waves-effect">Gỡ lỗi FFMPEG</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12">
            <h3>Cấu hình lưu trữ và CDN<br><hr></h3>
             <div class="alert alert-warning">
                <i class="fa fa-fw fa-exclamation-triangle"></i> <strong>Quan trọng:</strong> Bạn không thể bật hai hoặc ba bộ lưu trữ cùng lúc, nếu bạn bật FTP, amazon s3 sẽ tự động bị vô hiệu hóa, tương tự với amazon s3, Digitalocean và Google.
            </div>
            <div class="alert alert-info">
               <i class="fa fa-fw fa-exclamation-triangle"></i> <strong>Thông tin: </strong> Để biết thêm thông tin về cách thiết lập bộ nhớ của bên thứ ba, vui lòng truy cập <a href="https://docs.hisotechgroup.com/#idocs_storage" target="_blank">Tài liệu</a> page.
           </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình Amazon S3</h6>
                    <form class="general-settings" method="POST">
                        <div class="float-left">
                            <label for="amazone_s3" class="main-label">Lưu trữ Amazon S3</label>
                            <br><small class="admin-info">Bật Amazon Storage để lưu trữ tệp của bạn trên Amazon S3.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="amazone_s3" value="0" />
                            <input type="checkbox" name="amazone_s3" id="chck-amazone_s3" value="1" <?php echo ($wo['config']['amazone_s3'] == 1) ? 'checked': '';?>>
                            <label for="chck-amazone_s3" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên thùng Amazon</label>
                                <input type="text" id="bucket_name" name="bucket_name" class="form-control" value="<?php echo $wo['config']['bucket_name']?>">
                                <small class="admin-info">Amazon S3 của bạn <a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/creating-bucket.html" target="_blank">Tên thùng</a></small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Amazon S3 Khóa</label>
                                <input type="text" id="amazone_s3_key" name="amazone_s3_key" class="form-control" value="<?php echo $wo['config']['amazone_s3_key']?>">
                                <small class="admin-info">Khóa Amazon của bạn từ<a href="https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html" target="_blank">AWS giấy chứng nhận</a></small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa bí mật Amazon S3</label>
                                <input type="text" id="amazone_s3_s_key" name="amazone_s3_s_key" class="form-control" value="<?php echo $wo['config']['amazone_s3_s_key']?>">
                                <small class="admin-info">Bí mật Amazon của bạn từ <a href="https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html" target="_blank">AWS giấy chứng nhận</a></small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Điểm cuối tùy chỉnh Amazon S3 (Tùy chọn)</label>
                                <input type="text" name="amazon_endpoint" class="form-control" value="<?php echo ($wo['config']['amazon_endpoint']);?>">
                                <small class="admin-info">Tên miền tùy chỉnh Amazon của bạn, ví dụ: https://customCDNdomain.com</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <label for="region">Vùng thùng Amazon S3</label>
                        <select class="form-control show-tick" id="region" name="region">
                          <option value="us-east-2" <?php echo ($wo['config']['region'] == 'us-east-2')   ? ' selected' : '';?> >US East (Ohio) us-east-2</option>
                          <option value="us-east-1" <?php echo ($wo['config']['region'] == 'us-east-1')   ? ' selected' : '';?> >US East (N. Virginia) us-east-1</option>
                          <option value="us-west-1" <?php echo ($wo['config']['region'] == 'us-west-1')   ? ' selected' : '';?> >US West (N. California) us-west-1</option>
                          <option value="us-west-2" <?php echo ($wo['config']['region'] == 'us-west-2')   ? ' selected' : '';?> >US West (Oregon) us-west-2</option>
                          <option value="af-south-1" <?php echo ($wo['config']['region'] == 'af-south-1')   ? ' selected' : '';?> >Africa (Cape Town) af-south-1</option>
                          <option value="ap-east-1" <?php echo ($wo['config']['region'] == 'ap-east-1')   ? ' selected' : '';?> >Asia Pacific (Hong Kong) ap-east-1</option>
                          <option value="ap-south-1" <?php echo ($wo['config']['region'] == 'ap-south-1')   ? ' selected' : '';?> >Asia Pacific (Mumbai) ap-south-1</option>
                          <option value="ap-northeast-3" <?php echo ($wo['config']['region'] == 'ap-northeast-3')   ? ' selected' : '';?> >Asia Pacific (Osaka) ap-northeast-3</option>
                          <option value="ap-northeast-2" <?php echo ($wo['config']['region'] == 'ap-northeast-2')   ? ' selected' : '';?> >Asia Pacific (Seoul) ap-northeast-2</option>
                          <option value="ap-southeast-1" <?php echo ($wo['config']['region'] == 'ap-southeast-1')   ? ' selected' : '';?> >Asia Pacific (Singapore) ap-southeast-1</option>
                          <option value="ap-southeast-2" <?php echo ($wo['config']['region'] == 'ap-southeast-2')   ? ' selected' : '';?> >Asia Pacific (Sydney) ap-southeast-2</option>
                          <option value="ap-northeast-1" <?php echo ($wo['config']['region'] == 'ap-northeast-1')   ? ' selected' : '';?> >Asia Pacific (Tokyo) ap-northeast-1</option>
                          <option value="ca-central-1" <?php echo ($wo['config']['region'] == 'ca-central-1')   ? ' selected' : '';?> >Canada (Central) ca-central-1</option>
                          <option value="cn-northwest-1" <?php echo ($wo['config']['region'] == 'cn-northwest-1')   ? ' selected' : '';?> >China (Ningxia) cn-northwest-1</option>
                          <option value="eu-central-1" <?php echo ($wo['config']['region'] == 'eu-central-1')   ? ' selected' : '';?> >Europe (Frankfurt) eu-central-1</option>
                          <option value="eu-west-1" <?php echo ($wo['config']['region'] == 'eu-west-1')   ? ' selected' : '';?> >Europe (Ireland) eu-west-1</option>
                          <option value="eu-west-2" <?php echo ($wo['config']['region'] == 'eu-west-2')   ? ' selected' : '';?> >Europe (London) eu-west-2</option>
                          <option value="eu-south-1" <?php echo ($wo['config']['region'] == 'eu-south-1')   ? ' selected' : '';?> >Europe (Milan) eu-south-1</option>
                          <option value="eu-west-3" <?php echo ($wo['config']['region'] == 'eu-west-3')   ? ' selected' : '';?> >Europe (Paris) eu-west-3</option>
                          <option value="eu-north-1" <?php echo ($wo['config']['region'] == 'eu-north-1')   ? ' selected' : '';?> >Europe (Stockholm) eu-north-1</option>
                          <option value="ap-southeast-3" <?php echo ($wo['config']['region'] == 'ap-southeast-3')   ? ' selected' : '';?> >Asia Pacific (Jakarta) ap-southeast-3</option>
                          <option value="me-south-1" <?php echo ($wo['config']['region'] == 'me-south-1')   ? ' selected' : '';?> >Middle East(Bahrain) me-south-1</option>
                          <option value="sa-east-1" <?php echo ($wo['config']['region'] == 'sa-east-1')   ? ' selected' : '';?> >South America (São Paulo) sa-east-1</option>
                          <option value="us-gov-east-1" <?php echo ($wo['config']['region'] == 'us-gov-east-1')   ? ' selected' : '';?> >AWS GovCloud (US-East) us-gov-east-1</option>
                          <option value="us-gov-west-1" <?php echo ($wo['config']['region'] == 'us-gov-west-1')   ? ' selected' : '';?> >AWS GovCloud (US-West) us-gov-west-1</option>
                        </select>
                        <small class="admin-info">Vùng S3 của Amazon của bạn</small>
                        <div class="clearfix"></div>
                        <br>
                        <div class="alert alert-info">
                          Trước khi bật Amazon S3, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" lên bucket của mình. <br><br>
Trước khi tắt Amazon S3, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" xuống máy chủ.<br><br>
Chúng tôi khuyên bạn nên tải thư mục và tệp lên qua <a href="http://s3tools.org/s3cmd">S3cmd</a>.<br><br>
Nếu trang web của bạn vẫn còn mới, bạn có thể bỏ qua bước tải lên, nhưng hãy nhớ nhấp vào "Kiểm tra Kết nối".<br>
                        </div>
                        <div class="general-settings-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestS3()">Kiểm tra và xác minh kết nối</button>
                        <a href="<?php echo Wo_LoadAdminLinkSettings('upload-to-storage?storage=amazon'); ?>" class="btn btn-info m-t-15 waves-effect">Tải tệp lên Amazon</a>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình không gian Digitalocean</h6>
                    <form class="spaces-settings" method="POST">
                         <div class="float-left">
                            <label for="spaces" class="main-label">Lưu trữ không gian Digitalocean</label>
                            <br><small class="admin-info">Bật Digitalocean Storage để lưu trữ tệp của bạn trong Digitalocean Spaces.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="spaces" value="0" />
                            <input type="checkbox" name="spaces" id="chck-spaces" value="1" <?php echo ($wo['config']['spaces'] == 1) ? 'checked': '';?>>
                            <label for="chck-spaces" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên không gian Digitalocean</label>
                                <input type="text" id="space_name" name="space_name" class="form-control" value="<?php echo $wo['config']['space_name']?>">
                                <small class="admin-info">Tên Digitalocean Space Bucket của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Digitalocean Khóa</label>
                                <input type="text" id="spaces_key" name="spaces_key" class="form-control" value="<?php echo $wo['config']['spaces_key']?>">
                                <small class="admin-info">Khóa thông tin đăng nhập Digitalocean Space của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Digitalocean Secret</label>
                                <input type="text" id="spaces_secret" name="spaces_secret" class="form-control" value="<?php echo $wo['config']['spaces_secret']?>">
                                <small class="admin-info">Khóa bí mật cho thông tin đăng nhập Digitalocean Space của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Điểm cuối tùy chỉnh Digitalocean (Tùy chọn)</label>
                                <input type="text" name="spaces_endpoint" class="form-control" value="<?php echo ($wo['config']['spaces_endpoint']);?>">
                                <small class="admin-info">Tên miền tùy chỉnh Digitalocean của bạn, ví dụ: https://customCDNdomain.com</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <label for="space_region">Vùng xô Digitalocean</label>
                        <select class="form-control show-tick" id="space_region" name="space_region">
                          <option value="nyc1" <?php echo ($wo['config']['space_region'] == 'nyc1')   ? ' selected' : '';?> >New York [NYC1]</option>
                          <option value="nyc2" <?php echo ($wo['config']['space_region'] == 'nyc2')   ? ' selected' : '';?> >New York [NYC2]</option>
                          <option value="nyc3" <?php echo ($wo['config']['space_region'] == 'nyc3')   ? ' selected' : '';?> >New York [NYC3]</option>

                          <option value="sfo1" <?php echo ($wo['config']['space_region'] == 'sfo1')   ? ' selected' : '';?> >SAN FRANCISCO [SFO1]</option>
                          <option value="sfo2" <?php echo ($wo['config']['space_region'] == 'sfo2')   ? ' selected' : '';?> >SAN FRANCISCO [SFO2]</option>

                          <option value="tor1" <?php echo ($wo['config']['space_region'] == 'tor1')   ? ' selected' : '';?> >TORONTO [TOR1]</option>

                          <option value="lon1" <?php echo ($wo['config']['space_region'] == 'lon1')   ? ' selected' : '';?> >LONDON [LON1]</option>

                          <option value="FRA1" <?php echo ($wo['config']['space_region'] == 'FRA1')   ? ' selected' : '';?> >Frankfurt [FRA1]</option>


                          <option value="ams2" <?php echo ($wo['config']['space_region'] == 'ams2')   ? ' selected' : '';?> >Amsterdam [AMS2]</option>
                          <option value="ams3" <?php echo ($wo['config']['space_region'] == 'ams3')   ? ' selected' : '';?> >Amsterdam [AMS3]</option>
                          <option value="sgp1" <?php echo ($wo['config']['space_region'] == 'sgp1')   ? ' selected' : '';?> >Singapore [SGP1]</option>
                          <option value="blr1" <?php echo ($wo['config']['space_region'] == 'blr1')   ? ' selected' : '';?> >Bangalore [BLR1]</option>
                          
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <div class="alert alert-info">
                            Trước khi bật Digitalocean, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" lên bucket của mình. <br><br>
Trước khi tắt Digitalocean, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" xuống máy chủ. <br><br>
Nếu trang web của bạn vẫn còn mới, bạn có thể bỏ qua bước tải lên, nhưng hãy nhớ nhấp vào "Kiểm tra Kết nối". <br>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="spaces-settings-alert"></div>
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestSpaces()">Kiểm tra và xác minh kết nối</button>
                        <a href="<?php echo Wo_LoadAdminLinkSettings('upload-to-storage?storage=digitalocean'); ?>" class="btn btn-info m-t-15 waves-effect">Tải tệp lên Digitalocean</a>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình Wasabi</h6>
                    <div class="alert alert-warning">
                          <a href="https://knowledgebase.wasabi.com/hc/en-us/articles/13615396482203-Change-in-Ability-to-configure-PUBLIC-Access-to-objects-and-buckets">Wasabi gần đây đã triển khai các bản cập nhật để tăng cường các biện pháp bảo mật bằng cách vô hiệu hóa quyền truy cập công khai và thay đổi cấu hình liên quan đến khả năng truy cập của các đối tượng và thùng.</a>
                      </div>
                    <form class="wasabi_storage-settings" method="POST">
                         <div class="float-left">
                            <label for="wasabi_storage" class="main-label">Wasabi Lưu trữ</label>
                            <br><small class="admin-info">Bật Wasabi Storage để lưu trữ tệp của bạn trong Wasabi Spaces.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="wasabi_storage" value="0" />
                            <input type="checkbox" name="wasabi_storage" id="chck-wasabi_storage" value="1" <?php echo ($wo['config']['wasabi_storage'] == 1) ? 'checked': '';?> disabled>
                            <label for="chck-wasabi_storage" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Wasabi Bucket Name</label>
                                <input type="text" id="wasabi_bucket_name" name="wasabi_bucket_name" class="form-control" value="<?php echo $wo['config']['wasabi_bucket_name']?>" disabled>
                                <small class="admin-info">Your Wasabi Bucket Name.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa truy cập Wasabi</label>
                                <input type="text" id="wasabi_access_key" name="wasabi_access_key" class="form-control" value="<?php echo $wo['config']['wasabi_access_key']?>" disabled>
                                <small class="admin-info">Khóa truy cập Wasabi của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Bí quyết của Wasabi</label>
                                <input type="text" id="wasabi_secret_key" name="wasabi_secret_key" class="form-control" value="<?php echo $wo['config']['wasabi_secret_key']?>" disabled>
                                <small class="admin-info">Bí quyết Wasabi của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Điểm cuối tùy chỉnh Wasabi (Tùy chọn)</label>
                                <input type="text" name="wasabi_endpoint" class="form-control" value="<?php echo ($wo['config']['wasabi_endpoint']);?>" disabled>
                                <small class="admin-info">Tên miền tùy chỉnh Wasabi của bạn, ví dụ: https://customCDNdomain.com</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <label for="wasabi_bucket_region">Wasabi bucket region</label>
                        <select class="form-control show-tick" id="wasabi_bucket_region" name="wasabi_bucket_region" disabled>
                          <option value="us-west-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'us-west-1')   ? ' selected' : '';?> >us-west-1</option>
                          <option value="us-east-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'us-east-1')   ? ' selected' : '';?> >us-east-1</option>
                          <option value="us-east-2" <?php echo ($wo['config']['wasabi_bucket_region'] == 'us-east-2')   ? ' selected' : '';?> >us-east-2</option>
                          <option value="us-central-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'us-central-1')   ? ' selected' : '';?> >us-central-1</option>
                          <option value="ca-central-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'ca-central-1')   ? ' selected' : '';?> >ca-central-1</option>

                          <option value="eu-west-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'eu-west-1')   ? ' selected' : '';?> >eu-west-1</option>
                          <option value="eu-west-2" <?php echo ($wo['config']['wasabi_bucket_region'] == 'eu-west-2')   ? ' selected' : '';?> >eu-west-2</option>
                          <option value="eu-central-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'eu-central-1')   ? ' selected' : '';?> >eu-central-1</option>
                          <option value="eu-central-2" <?php echo ($wo['config']['wasabi_bucket_region'] == 'eu-central-2')   ? ' selected' : '';?> >eu-central-2</option>

                          <option value="ap-northeast-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'ap-northeast-1')   ? ' selected' : '';?> >ap-northeast-1</option>
                          <option value="ap-northeast-2" <?php echo ($wo['config']['wasabi_bucket_region'] == 'ap-northeast-2')   ? ' selected' : '';?> >ap-northeast-2</option>
                          <option value="ap-southeast-2" <?php echo ($wo['config']['wasabi_bucket_region'] == 'ap-southeast-2')   ? ' selected' : '';?> >ap-southeast-2</option>
                          <option value="ap-southeast-1" <?php echo ($wo['config']['wasabi_bucket_region'] == 'ap-southeast-1')   ? ' selected' : '';?> >ap-southeast-1</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <div class="alert alert-info">
                            Trước khi bật Wasabi, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" lên bucket của mình. <br><br>
Trước khi tắt Wasabi, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" lên máy chủ. <br><br>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="wasabi_storage_alert"></div>
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestWasabi()">Kiểm tra và xác minh kết nối</button>
                        <a href="<?php echo Wo_LoadAdminLinkSettings('upload-to-storage?storage=wasabi'); ?>" class="btn btn-info m-t-15 waves-effect">Tải tệp lên Wasabi</a>

                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt FTP</h6>
                    <small>Bạn có thể tải tệp trực tiếp từ máy chủ của mình lên máy chủ FTP khác và tải chúng từ đó.</small><br>
                    <small>Quan trọng: Điều này có thể làm chậm tốc độ tải lên/xóa trang web của bạn, hãy đảm bảo sử dụng máy chủ FTP nhanh.</small><br><br>
                    <form class="ftp-settings" method="POST">
                         <div class="float-left">
                            <label for="ftp_upload" class="main-label">Lưu trữ FTP</label>
                            <br><small class="admin-info">Bật FTP Storage để lưu trữ tệp của bạn trên máy chủ FTP của riêng bạn.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="ftp_upload" value="0" />
                            <input type="checkbox" name="ftp_upload" id="chck-ftp_upload" value="1" <?php echo ($wo['config']['ftp_upload'] == 1) ? 'checked': '';?>>
                            <label for="chck-ftp_upload" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên máy chủ FTP</label>
                                <input type="text" id="ftp_host" name="ftp_host" class="form-control" value="<?php echo $wo['config']['ftp_host']?>">
                                <small class="admin-info">Tên máy chủ FTP của bạn có thể là IP hoặc tên miền.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">FTP Tên người dùng</label>
                                <input type="text" id="ftp_username" name="ftp_username" class="form-control" value="<?php echo $wo['config']['ftp_username']?>">
                                <small class="admin-info">Tên người dùng tài khoản FTP của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">FTP Mật khẩu</label>
                                <input type="text" id="ftp_password" name="ftp_password" class="form-control" value="<?php echo $wo['config']['ftp_password']?>">
                                <small class="admin-info">Mật khẩu tài khoản FTP của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">FTP Cổng</label>
                                <input type="text" id="ftp_port" name="ftp_port" class="form-control" value="<?php echo $wo['config']['ftp_port']?>">
                                <small class="admin-info">Cổng máy chủ FTP của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">FTP Đường dẫn</label>
                                <input type="text" id="ftp_path" name="ftp_path" class="form-control" value="<?php echo $wo['config']['ftp_path']?>">
                                <small class="admin-info">Đường dẫn đến /upload files.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">FTP Điểm cuối</label>
                                <input type="text" id="ftp_endpoint" name="ftp_endpoint" class="form-control" value="<?php echo $wo['config']['ftp_endpoint']?>">
                                <small class="admin-info">IP hoặc tên miền mà máy chủ FTP được trỏ đến, ví dụ: wowonderftpstorage.com</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="alert alert-info">
                            Trước khi bật FTP, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" lên máy chủ FTP.<br><br>
Trước khi tắt FTP, hãy đảm bảo bạn đã tải toàn bộ thư mục "upload/" xuống máy chủ.<br><br>
Nếu trang web của bạn vẫn còn mới, bạn có thể bỏ qua bước tải lên, nhưng hãy nhớ nhấp vào "Kiểm tra Kết nối".<br>
                        </div>
                        <div class="ftp-settings-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">

                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestFTP()">Test FTP Connection</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt Google Cloud</h6>

                    <form class="drive-settings" method="POST">
                         <div class="float-left">
                            <label for="cloud_upload" class="main-label">Lưu trữ đám mây của Google</label>
                            <br><small class="admin-info">Bật Google Cloud Storage để lưu trữ tệp của bạn trên Google Cloud.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="cloud_upload" value="0" />
                            <input type="checkbox" name="cloud_upload" id="chck-cloud_upload" value="1" <?php echo ($wo['config']['cloud_upload'] == 1) ? 'checked': '';?>>
                            <label for="chck-cloud_upload" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên nhóm Google Cloud</label>
                                <input type="text" id="cloud_bucket_name" name="cloud_bucket_name" class="form-control" value="<?php echo $wo['config']['cloud_bucket_name']?>">
                                <small class="admin-info">Mật khẩu tài khoản FTP của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line focused">
                                <label class="form-label">Google Cloud Tệp</label>
                                <input type="file" id="cloud_file" name="cloud_file" class="form-control">
                                <small class="admin-info">Phải là một tệp JSON.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Đường dẫn tệp Google Cloud</label>
                                <input type="text" id="cloud_file_path" class="form-control" value="<?php echo $wo['config']['cloud_file_path']?>" readonly>
                                <small class="admin-info">Đường dẫn đến Google Cloud File trên máy chủ của bạn.</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Điểm cuối tùy chỉnh của Google Cloud (Tùy chọn)</label>
                                <input type="text" name="cloud_endpoint" class="form-control" value="<?php echo ($wo['config']['cloud_endpoint']);?>">
                                <small class="admin-info">Tên miền tùy chỉnh Google Cloud của bạn, ví dụ: https://customCDNdomain.com</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="alert alert-info">
                            Hãy đảm bảo bạn tải toàn bộ thư mục "upload/" lên bucket của mình.<br><br>
Hãy đảm bảo giữ (Tệp Google Cloud) trên máy chủ của bạn. trong Đường dẫn Tệp Google Cloud (<?php echo $wo['config']['cloud_file_path']?>)<br>
                        </div>
                        <div class="drive-settings-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestCloud()">Test Cloud Connection</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình Backblaze</h6>
                    <form class="backblaze_storage-settings" method="POST">
                         <div class="float-left">
                            <label for="backblaze_storage" class="main-label">Lưu trữ Backblaze</label>
                            <br><small class="admin-info">Bật Backblaze Storage để lưu trữ tệp của bạn trong Backblaze Spaces.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="backblaze_storage" value="0" />
                            <input type="checkbox" name="backblaze_storage" id="chck-backblaze_storage" value="1" <?php echo ($wo['config']['backblaze_storage'] == '1') ? 'checked': '';?>>
                            <label for="chck-backblaze_storage" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID nhóm Backblaze</label>
                                <input type="text" id="backblaze_bucket_id" name="backblaze_bucket_id" class="form-control" value="<?php echo $wo['config']['backblaze_bucket_id']?>">
                                <small class="admin-info">ID nhóm Backblaze của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên nhóm Backblaze</label>
                                <input type="text" id="backblaze_bucket_name" name="backblaze_bucket_name" class="form-control" value="<?php echo $wo['config']['backblaze_bucket_name']?>">
                                <small class="admin-info">Tên nhóm Backblaze của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khu vực Xô Backblaze</label>
                                <input type="text" id="backblaze_bucket_region" name="backblaze_bucket_region" class="form-control" value="<?php echo $wo['config']['backblaze_bucket_region']?>">
                                <small class="admin-info">Khu vực Backblaze Bucket của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ID khóa truy cập Backblaze</label>
                                <input type="text" id="backblaze_access_key_id" name="backblaze_access_key_id" class="form-control" value="<?php echo $wo['config']['backblaze_access_key_id'] ?>">
                                <small class="admin-info">ID khóa truy cập Backblaze của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa truy cập Backblaze</label>
                                <input type="text" id="backblaze_access_key" name="backblaze_access_key" class="form-control" value="<?php echo $wo['config']['backblaze_access_key'] ?>">
                                <small class="admin-info">Khóa truy cập Backblaze của bạn.</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Điểm cuối tùy chỉnh Backblaze (Tùy chọn)</label>
                                <input type="text" name="backblaze_endpoint" class="form-control" value="<?php echo ($wo['config']['backblaze_endpoint']);?>">
                                <small class="admin-info">Tên miền tùy chỉnh Backblaze của bạn, ví dụ: https://customCDNdomain.com</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br>
                        <div class="alert alert-info">
                            Trước khi bật Backblaze, hãy đảm bảo bạn tải toàn bộ thư mục "upload/" lên bucket của mình. <br><br>
Trước khi tắt Backblaze, hãy đảm bảo bạn tải toàn bộ thư mục "upload/" lên máy chủ. <br><br>
                        </div>
                        <div class="backblaze_storage_alert"></div>
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestBackblaze()">Kiểm tra và xác minh kết nối</button>
                        <a href="<?php echo Wo_LoadAdminLinkSettings('upload-to-storage?storage=backblaze'); ?>" class="btn btn-info m-t-15 waves-effect">Tải tệp lên BackBlaze</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
function Wo_TestBackblaze() {
    $('form.backblaze_storage-settings').find('.btn-success').text('Vui lòng chờ...');
    $('.backblaze_storage_alert').empty();
    $.get(Wo_Ajax_Requests_File() + '?f=admin_setting&s=test_backblaze', function (data) {
        if (data.status == 200) {
            $('.backblaze_storage_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Connection established!</div>');
            setTimeout(function () {
                $('.backblaze_storage_alert').empty();
            }, 5000);
        } else if (data.status == 300) {
            $('.backblaze_storage_alert').html('<div class="alert alert-danger">Bucket doesn\'t exists</div>');
            // setTimeout(function () {
            //     $('.backblaze_storage_alert').empty();
            // }, 5000);
        } else if (data.status == 500) {
            $('.backblaze_storage_alert').html('<div class="alert alert-danger">Your s3 account doesn\'t have any buckets, please create one.</div>');
            // setTimeout(function () {
            //     $('.backblaze_storage_alert').empty();
            // }, 5000);
        } else if (data.status == 400) {
            $('.backblaze_storage_alert').html('<div class="alert alert-danger">'+data.message+'</div>');
            // setTimeout(function () {
            //     $('.backblaze_storage_alert').empty();
            // }, 5000);
        } else  {
            $('.backblaze_storage_alert').html('<div class="alert alert-danger">Error while connecting to Backblaze, please check your details</div>');
            // setTimeout(function () {
            //     $('.backblaze_storage_alert').empty();
            // }, 5000);
        }
        $('form.backblaze_storage-settings').find('.btn-success').text('Test & Verify Connection');
    });
}
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
});

function Wo_TestWasabi() {
    $('form.wasabi_storage-settings').find('.btn-success').text('Vui lòng chờ...');
    $('.wasabi_storage_alert').empty();
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_wasabi'}, function (data) {
        if (data.status == 200) {
            $('.wasabi_storage_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Connection established!</div>');
            setTimeout(function () {
                $('.wasabi_storage_alert').empty();
            }, 5000);
        } else if (data.status == 300) {
            $('.wasabi_storage_alert').html('<div class="alert alert-danger">Bucket doesn\'t exists</div>');
            // setTimeout(function () {
            //     $('.wasabi_storage_alert').empty();
            // }, 5000);
        } else if (data.status == 500) {
            $('.wasabi_storage_alert').html('<div class="alert alert-danger">Your s3 account doesn\'t have any buckets, please create one.</div>');
            // setTimeout(function () {
            //     $('.wasabi_storage_alert').empty();
            // }, 5000);
        } else if (data.status == 400) {
            $('.wasabi_storage_alert').html('<div class="alert alert-danger">'+data.message+'</div>');
            // setTimeout(function () {
            //     $('.wasabi_storage_alert').empty();
            // }, 5000);
        } else  {
            $('.wasabi_storage_alert').html('<div class="alert alert-danger">Error while connecting to amazone, please check your details</div>');
            // setTimeout(function () {
            //     $('.wasabi_storage_alert').empty();
            // }, 5000);
        }
        $('form.wasabi_storage-settings').find('.btn-success').text('Test & Verify Connection');
    });
}
function Wo_TestCloud() {
    $('form.drive-settings').find('.btn-success').text('Vui lòng chờ...');
    $('.drive-settings-alert').empty();
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_cloud'}, function (data) {
        if (data.status == 200) {
            $('.drive-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Connection established!</div>');
            setTimeout(function () {
                $('.drive-settings-alert').empty();
            }, 5000);
        } else {
            $('.drive-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
            // setTimeout(function () {
            //     $('.drive-settings-alert').empty();
            // }, 2000);
        }
        $('form.drive-settings').find('.btn-success').text('Test Cloud Connection');
    });
}
function Wo_TestS3() {
	$('form.general-settings').find('.btn-success').text('Vui lòng chờ...');
    $('.general-settings-alert').empty();
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_s3'}, function (data) {
		if (data.status == 200) {
            $('.general-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Connection established!</div>');
            setTimeout(function () {
                $('.general-settings-alert').empty();
            }, 5000);
		} else if (data.status == 300) {
            $('.general-settings-alert').html('<div class="alert alert-danger">Bucket doesn\'t exists</div>');
            // setTimeout(function () {
            //     $('.general-settings-alert').empty();
            // }, 5000);
		} else if (data.status == 500) {
            $('.general-settings-alert').html('<div class="alert alert-danger">Your s3 account doesn\'t have any buckets, please create one.</div>');
            // setTimeout(function () {
            //     $('.general-settings-alert').empty();
            // }, 5000);
		} else if (data.status == 400) {
			$('.general-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
            // setTimeout(function () {
            //     $('.general-settings-alert').empty();
            // }, 5000);
		} else  {
            $('.general-settings-alert').html('<div class="alert alert-danger">Error while connecting to amazone, please check your details</div>');
            // setTimeout(function () {
            //     $('.general-settings-alert').empty();
            // }, 5000);
		}
		$('form.general-settings').find('.btn-success').text('Test & Verify Connection');
	});
}

function Wo_TestSpaces() {
    $('form.spaces-settings').find('.btn-success').text('Vui lòng chờ...');
    $('.spaces-settings-alert').empty();
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_spaces'}, function (data) {
        if (data.status == 200) {
            $('.spaces-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Connection established!</div>');
            setTimeout(function () {
                $('.spaces-settings-alert').empty();
            }, 5000);
        } else if (data.status == 300) {
            $('.spaces-settings-alert').html('<div class="alert alert-danger">Bucket doesn\'t exists</div>');
            // setTimeout(function () {
            //     $('.spaces-settings-alert').empty();
            // }, 2000);
        } else if (data.status == 500) {
            $('.spaces-settings-alert').html('<div class="alert alert-danger">Your s3 account doesn\'t have any buckets, please create one.</div>');
            // setTimeout(function () {
            //     $('.spaces-settings-alert').empty();
            // }, 2000);
        } else if (data.status == 400) {
            $('.spaces-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
            // setTimeout(function () {
            //     $('.spaces-settings-alert').empty();
            // }, 2000);
        } else  {
            $('.spaces-settings-alert').html('<div class="alert alert-danger">Error while connecting to amazone, please check your details</div>');
            // setTimeout(function () {
            //     $('.spaces-settings-alert').empty();
            // }, 2000);
        }
        $('form.spaces-settings').find('.btn-success').text('Test Connection');
    });
}
function Wo_TestFTP() {
    $('form.ftp-settings').find('.btn-success').text('Vui lòng chờ...');
    $('.ftp-settings-alert').empty();
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_ftp'}, function (data) {
        if (data.status == 200) {
            $('.ftp-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Connection established!</div>');
            setTimeout(function () {
                $('.ftp-settings-alert').empty();
            }, 5000);
        } else if (data.status == 400) {
            $('.ftp-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
            // setTimeout(function () {
            //     $('.ftp-settings-alert').empty();
            // }, 2000);
        }
        $('form.ftp-settings').find('.btn-success').text('Test FTP Connection');
    });
}

$(function() {

    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        if (configName == 'ffmpeg_system') {
            setToTrue = 'off';
            if ($(this).is(":checked") === true) {
                setToTrue = 'on';
            }
        }
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
	
	$('.round_check input[type=radio]').on('change', function() {
		clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
	
    $('input[type=text], input[type=number]').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));

    $('input[type=file]').on('change', function(){
        var objData = new FormData();
        var thisElement = $(this);
        var file = $(this)[0].files[0];
        var hash_id = $('input[name=hash_id]').val();
        objData.append('cloud_file', file);
        objData.append('hash_id', hash_id);
        thisElement.addClass('warning');
        $('.drive-settings-alert').html(' ');
        if (file.type == 'application/json') {
            $.ajax({
              url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
              type: 'post',
              data: objData,
              contentType: false,
              processData: false,
              success: function(response){
                thisElement.removeClass('warning');
                thisElement.addClass('success');
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
              },
           });
        } else {
            thisElement.addClass('error');
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('error');
            }, 2000);
            $('.drive-settings-alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> File format should be .json</div>');
        }
    });

    var debug_settings = $('form.debug-settings');
    debug_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=ffmpeg_debug',
        beforeSend: function() {
            debug_settings.find('.waves-effect').text("Please wait..");
        },
        success: function(data) {
            if (data.status == 200) {
                debug_settings.find('.waves-effect').text('Debug');
                $('#debug_ffmpeg').val(data.data);
                if (data.video_url) {
                    $('.debug-settings-alert').html('<div class="alert alert-success"><a href="'+data.video_url+'" target="_blank">You can check the converted video test_240p_converted.mp4</a></div>');
                }
            }
        }
    });
});

</script>
