<div class="container-fluid">
    <div>
        <h3>Cấu hình chung</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Cài đặt</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Cấu hình chung</li>
            </ol>
        </nav>
    </div>
    <?php $getStatus = getStatus(); if (!empty($getStatus) && !empty(checkIfThereIsError($getStatus))) {?><div class="alert alert-danger"><strong>Important!</strong> There are some errors found on your system, please review <a href="<?php echo Wo_LoadAdminLinkSettings('system_status'); ?>" data-ajax="?path=system_status">System Status</a>.</div><?php }?>
    <!-- Vertical Layout -->
    <?php if ($wo['config']['website_mode'] != 'facebook') { ?>
        <div class="alert alert-warning">Lưu ý: Một số tính năng bị vô hiệu hóa do chế độ trang web bạn sử dụng.</div>
    <?php } ?>
    <div class="row">
        <div class="col-lg-6 col-md-6 float-left">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình chung</h6>
                    <form class="general-settings" method="POST">
                        <div class="float-left">
                            <label for="developer_mode" class="main-label">Chế độ nhà phát triển</label>
                            <br><small class="admin-info">Bằng cách bật chế độ nhà phát triển, báo cáo lỗi sẽ được bật, <br>không nên bật chế độ này nếu không có sự trợ giúp của nhà phát triển,<br>điều này có thể gây ra một số vấn đề trên trang web của bạn.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="developer_mode" value="0" />
                            <input type="checkbox" name="developer_mode" id="chck-developer_mode" value="1" <?php echo ($wo['config']['developer_mode'] == 1) ? 'checked': '';?>>
                            <label for="chck-developer_mode" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="cacheSystem" class="main-label">Hệ thống bộ nhớ đệm</label>
                            <br><small class="admin-info">Bằng cách bật Hệ thống bộ nhớ đệm, hãy tăng tốc trang web của bạn lên đến 80%! <br>Lưu ý: Bộ nhớ đệm thư mục và tất cả quyền của thư mục con phải được đặt thành 777.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="cacheSystem" value="0" />
                            <input type="checkbox" name="cacheSystem" id="chck-cacheSystem" value="1" <?php echo ($wo['config']['cacheSystem'] == 1) ? 'checked': '';?>>
                            <label for="chck-cacheSystem" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="maintenance_mode" class="main-label">Chế độ bảo trì</label>
                            <br><small class="admin-info">Chuyển toàn bộ trang web sang chế độ Bảo trì. <br> Bạn có thể khôi phục trang web bằng cách truy cập /admincp hoặc /admin-cp</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="maintenance_mode" value="0" />
                            <input type="checkbox" name="maintenance_mode" id="chck-maintenance_mode" value="1" <?php echo ($wo['config']['maintenance_mode'] == 1) ? 'checked': '';?>>
                            <label for="chck-maintenance_mode" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="useSeoFrindly" class="main-label">URL thân thiện với SEO</label>
                            <br><small class="admin-info">Cho phép tải mượt mà để tiết kiệm băng thông.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="useSeoFrindly" value="0" />
                            <input type="checkbox" name="useSeoFrindly" id="chck-useSeoFrindly" value="1" <?php echo ($wo['config']['useSeoFrindly'] == 1) ? 'checked': '';?>>
                            <label for="chck-useSeoFrindly" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="developers_page" class="main-label">Nhà phát triển (Hệ thống API)</label>
                            <br><small class="admin-info">Hiển thị trang /developers cho tất cả người dùng để yêu cầu API.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="developers_page" value="0" />
                            <input type="checkbox" name="developers_page" id="chck-developers_page" value="1" <?php echo ($wo['config']['developers_page'] == 1) ? 'checked': '';?>>
                            <label for="chck-developers_page" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="profile_privacy" class="main-label">Trang chào mừng người dùng</label>
                            <br><small class="admin-info">Cho phép người dùng chưa đăng nhập xem hồ sơ người dùng trên trang chào mừng.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="profile_privacy" value="0" />
                            <input type="checkbox" name="profile_privacy" id="chck-profile_privacy" value="1" <?php echo ($wo['config']['profile_privacy'] == 1) ? 'checked': '';?>>
                            <label for="chck-profile_privacy" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <label for="defualtLang" class="main-label">Ngôn ngữ mặc định</label>
                        <br><small class="admin-info">Đặt ngôn ngữ mặc định cho trang web của bạn.</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="defualtLang" name="defualtLang">
                                <?php
                                 foreach (Wo_LangsNamesFromDB() as $lang) {
                                    
                                   $languages = $lang;
                                    
                                   $languages_name = ucfirst(strtolower($languages));
                                    
                                   $selected_lang = ($languages == $wo['config']['defualtLang']) ? ' selected' : '';
                                    
                                 ?>
                              <option value="<?php echo $languages;?>"<?php echo $selected_lang;?> ><?php echo $languages_name;?></option>
                              <?php } ?>
                            </select>
                        </div>
                        <hr>
                        <label for="date_style" class="main-label">Định dạng ngày tháng</label>
                        <br><small class="admin-info">Đặt định dạng ngày mặc định cho trang web của bạn.</small>
                        <select class="form-control show-tick" id="date_style" name="date_style">
                          <option value="m-d-y" <?php if($wo['config']['date_style'] == 'm-d-y'){echo 'selected';};?> >mm-dd-yy</option>
                          <option value="d-m-y" <?php if($wo['config']['date_style'] == 'd-m-y'){echo 'selected';};?> >dd-mm-yy</option>
                          <option value="y-m-d" <?php if($wo['config']['date_style'] == 'y-m-d'){echo 'selected';};?> >yy-mm-dd</option>
                          <option value="M-d-y" <?php if($wo['config']['date_style'] == 'M-d-y'){echo 'selected';};?> >mmm-dd-yy</option>      
                          <option value="d-F-y" <?php if($wo['config']['date_style'] == 'd-F-y'){echo 'selected';};?> >dd-mmmm-yy</option>
                          <option value="Y-m-d" <?php if($wo['config']['date_style'] == 'Y-m-d'){echo 'selected';};?> >yyyy-mm-dd</option> 
                          <option value="d-M-Y" <?php if($wo['config']['date_style'] == 'd-M-Y'){echo 'selected';};?> >dd-mmm-yyyy</option>
                          <option value="d-F-Y" <?php if($wo['config']['date_style'] == 'd-F-Y'){echo 'selected';};?> >dd-mmmm-yyyy</option>
                        </select>
                        <hr>

                        <label for="directory_landing_page">Trang đích</label>
                        <select class="form-control show-tick" id="directory_landing_page" name="directory_landing_page">
                          <option value="welcome" <?php echo ($wo['config']['directory_landing_page'] == 'welcome')   ? ' selected' : '';?> >Trang đăng nhập</option>
                          <option value="register" <?php echo ($wo['config']['directory_landing_page'] == 'register')   ? ' selected' : '';?> >Trang đăng ký</option>
                          <option value="home" <?php echo ($wo['config']['directory_landing_page'] == 'home')   ? ' selected' : '';?> >Trang Nguồn cấp tin tức</option>
                          <option value="directory" <?php echo ($wo['config']['directory_landing_page'] == 'directory')   ? ' selected' : '';?> >Trang thư mục</option>
                        </select>
                        <small class="admin-info">Nếu mọi người không đăng nhập, họ sẽ được chuyển hướng đến trang này.</small>
                        
                        <!-- <div class="general-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
              <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình người dùng</h6>
                    <form class="user2-settings" method="POST">
                        <div class="float-left">
                            <label for="online_sidebar" class="main-label">Người dùng trực tuyến</label>
                        <br><small class="admin-info">Hiển thị người dùng đang hoạt động hiện tại trên trang chủ.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="online_sidebar" value="0" />
                            <input type="checkbox" name="online_sidebar" id="chck-online_sidebar" value="1" <?php echo ($wo['config']['online_sidebar'] == 1) ? 'checked': '';?>>
                            <label for="chck-online_sidebar" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="user_lastseen" class="main-label">Trạng thái nhìn thấy lần cuối của người dùng</label>
                           <br><small class="admin-info">Cho phép người dùng thiết lập trạng thái trực tuyến và hoạt động lần cuối.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="user_lastseen" value="0" />
                            <input type="checkbox" name="user_lastseen" id="chck-user_lastseen" value="1" <?php echo ($wo['config']['user_lastseen'] == 1) ? 'checked': '';?>>
                            <label for="chck-user_lastseen" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="deleteAccount" class="main-label">Xóa tài khoản người dùng</label>
                            <br><small class="admin-info">Cho phép người dùng xóa tài khoản của họ.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="deleteAccount" value="0" />
                            <input type="checkbox" name="deleteAccount" id="chck-deleteAccount" value="1" <?php echo ($wo['config']['deleteAccount'] == 1) ? 'checked': '';?>>
                            <label for="chck-deleteAccount" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="profile_back" class="main-label">Thay đổi nền hồ sơ </label>
                            <select class="form-control show-tick" id="profile_background_request" name="profile_background_request" onchange="SelectProModel('can_use_background',this)">
                              <option value="admin" <?php echo ($wo['config']['profile_background_request'] == 'admin')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"> <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path> <circle cx="12" cy="7" r="4"></circle> </svg>Admin</option>
                              <option value="all" <?php echo ($wo['config']['profile_background_request'] == 'all')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe"> <circle cx="12" cy="12" r="10"></circle> <line x1="2" y1="12" x2="22" y2="12"></line> <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path> </svg> Tất cả người dùng</option>
                              <option value="verified" <?php echo ($wo['config']['profile_background_request'] == 'verified')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="verified-color feather feather-check-circle" title="" data-toggle="tooltip" data-original-title="Verified User"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z"></path></svg>Chỉ dành cho người dùng đã xác minh</option>
                              <option value="pro" <?php echo ($wo['config']['profile_background_request'] == 'pro')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2V13H10V22L17,10H13L17,2H7Z"></path></svg>Chỉ dành cho người dùng chuyên nghiệp</option>
                            </select>
                            <br><small class="admin-info">Cho phép người dùng thay đổi hình nền hồ sơ bằng cách tải lên hình ảnh.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="profile_back" value="0" />
                            <input type="checkbox" name="profile_back" id="chck-profile_back" value="1" <?php echo ($wo['config']['profile_back'] == 1) ? 'checked': '';?>>
                            <label for="chck-profile_back" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                         <div class="float-left">
                            <label for="connectivitySystem" class="main-label">Hệ thống bạn bè</label>
                        <br><small class="admin-info">Chọn giữa hệ thống Theo dõi và Bạn bè. <br> <span style="color: #c48a36">Nếu bạn thay đổi hệ thống sang hệ thống khác, tất cả những người đang theo dõi, người theo dõi, bạn bè hiện tại sẽ bị xóa.</span></small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="connectivitySystem" value="0" />
                            <input type="checkbox" name="connectivitySystem" id="chck-connectivitySystem" value="1" <?php echo ($wo['config']['connectivitySystem'] == 1) ? 'checked': '';?>>
                            <label for="chck-connectivitySystem" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="form-line">
                                <label class="form-label" class="main-label">Giới hạn hệ thống kết nối</label>
                                <input type="text" name="connectivitySystemLimit" class="form-control" value="<?php echo $wo['config']['connectivitySystemLimit']?>"><small class="admin-info">Mỗi người dùng có thể có bao nhiêu bạn bè?</small>
                            </div>
                        </div>
                        <hr>
                        
                         <div class="float-left">
                            <label for="invite_links_system" class="main-label">Hệ thống mời người dùng</label>
                            <br><small class="admin-info">Cho phép người dùng mời người dùng khác vào trang web của bạn.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="invite_links_system" value="0" />
                            <input type="checkbox" name="invite_links_system" id="chck-invite_links_system" value="1" <?php echo ($wo['config']['invite_links_system'] == 1) ? 'checked': '';?>>
                            <label for="chck-invite_links_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <label class="form-label" class="main-label">Người dùng có thể tạo bao nhiêu liên kết?</label>
                            <div class="form-line">
                                <input type="text" id="user_links_limit" name="user_links_limit" class="form-control" value="<?php echo $wo['config']['user_links_limit']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <label class="form-label" class="main-label">Người dùng có thể tạo X liên kết trong?</label>
                            <div class="form-line">
                                <select class="form-control show-tick" id="expire_user_links" name="expire_user_links">
                                      <option value="hour" <?php echo ($wo['config']['expire_user_links'] == 'hour')   ? ' selected': '';?>>1 Giờ</option>
                                      <option value="day" <?php echo ($wo['config']['expire_user_links'] == 'day')   ? ' selected': '';?>>1 Ngày</option>
                                      <option value="week" <?php echo ($wo['config']['expire_user_links'] == 'week')   ? ' selected': '';?>>1 Tuần</option>
                                      <option value="month" <?php echo ($wo['config']['expire_user_links'] == 'month')   ? ' selected': '';?>>1 Tháng</option>
                                      <option value="year" <?php echo ($wo['config']['expire_user_links'] == 'year')   ? ' selected': '';?>>1 Năm</option>
                                </select>
                            </div>
                        </div>
                        <!-- <div class="user2-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt khác</h6>
                    <div class="other-settings-alert"></div>
                    <form class="other-settings" method="POST">
                        <div class="form-group form-float">
                            <label class="form-label">Từ ngữ bị kiểm duyệt</label>
                            <div class="form-line">
                                <input type="text" id="censored_words" name="censored_words" class="form-control" value="<?php echo $wo['config']['censored_words']?>">
                                <small class="admin-info">Các từ sẽ bị kiểm duyệt và thay thế bằng *** trong tin nhắn, bài đăng, bình luận, v.v., được phân tách bằng dấu phẩy.</small>
                            </div>
                        </div>
                        <label for="cache_sidebar" >Bộ nhớ đệm trang chủ</label>
                        <select class="form-control show-tick" id="cache_sidebar" name="cache_sidebar">
                          <option value="1" <?php echo ($wo['config']['cache_sidebar'] == 1)   ? ' selected' : '';?> >Cập nhật dữ liệu thanh bên trang chủ sau mỗi 2 phút (tải nhanh hơn)</option>
                          <option value="0" <?php echo ($wo['config']['cache_sidebar'] == 0)   ? ' selected' : '';?> >Không bao giờ lưu vào bộ nhớ đệm, luôn luôn lấy dữ liệu mới</option>
                        </select>
                        <small class="admin-info">Bật tính năng này để tiết kiệm dung lượng sử dụng MySQL và tăng tốc độ trang chủ. </small>
                        <div class="clearfix"></div>
                        <label for="update_user_profile" >Bộ nhớ đệm trang hồ sơ</label>
                        <div class="form-group">
                            <select class="form-control show-tick" id="update_user_profile" name="update_user_profile">
                              <option value="30" <?php echo ($wo['config']['update_user_profile'] == 30)   ? ' selected' : '';?> >Cứ 30 giây</option>
                              <option value="120" <?php echo ($wo['config']['update_user_profile'] == 120)   ? ' selected' : '';?> >Cứ 2 phút một lần</option>
                              <option value="3600" <?php echo ($wo['config']['update_user_profile'] == 3600)   ? ' selected' : '';?> >Mỗi 1 giờ</option>
                              <option value="7200" <?php echo ($wo['config']['update_user_profile'] == 7200)   ? ' selected' : '';?> >Mỗi 2 giờ</option>
                              <option value="43200" <?php echo ($wo['config']['update_user_profile'] == 43200)   ? ' selected' : '';?> >Mỗi 12 giờ</option>
                              <option value="86400" <?php echo ($wo['config']['update_user_profile'] == 86400)   ? ' selected' : '';?> >Mỗi 24 giờ</option>
                            </select>
                            <small class="admin-info margin-top-5">Cập nhật dữ liệu thanh bên sau mỗi X, điều này liên quan đến hệ thống bộ nhớ đệm để tiết kiệm dung lượng sử dụng MySQL.</small>
                        </div>
                        <div class="form-group form-float">
                            <label class="form-label">Khóa API Exchangerate</label>
                            <div class="form-line">
                                <input type="text" id="exchangerate_key" name="exchangerate_key" class="form-control" value="<?php echo $wo['config']['exchangerate_key']?>">
                                <small class="admin-info">Khóa API Exchangerate của bạn từ <a href="https://app.exchangerate-api.com/dashboard">ở đây</a></small>
                            </div>
                        </div>
                        <hr>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            
        </div>
        <div class="col-lg-6 col-md-6 float-right">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Đăng nhập & Đăng ký</h6>
                    <form class="user-settings" method="POST">
                        <div class="float-left">
                            <label for="user_registration" class="main-label">Đăng ký người dùng</label>
                            <br><small class="admin-info">Cho phép người dùng tạo tài khoản trên trang web của bạn.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="user_registration" value="0" />
                            <input type="checkbox" name="user_registration" id="chck-user_registration" value="1" <?php echo ($wo['config']['user_registration'] == 1) ? 'checked': '';?>>
                            <label for="chck-user_registration" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="auto_username" class="main-label">Tên người dùng tự động khi đăng ký</label>
                            <br><small class="admin-info">Tạo tên người dùng tự động khi đăng ký. <br> Biểu mẫu đăng ký sẽ yêu cầu tên và họ của người dùng.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="auto_username" value="0" />
                            <input type="checkbox" name="auto_username" id="chck-auto_username" value="1" <?php echo ($wo['config']['auto_username'] == 1) ? 'checked': '';?>>
                            <label for="chck-auto_username" class="check-trail"><span class="check-handler"></span></label>
                        </div> 
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="password_complexity_system" class="main-label">Hệ thống độ phức tạp của mật khẩu</label>
                            <br><small class="admin-info">Hệ thống sẽ yêu cầu mật khẩu mạnh khi đăng ký, <br>bao gồm chữ cái, số và ký tự đặc biệt.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="password_complexity_system" value="0" />
                            <input type="checkbox" name="password_complexity_system" id="chck-password_complexity_system" value="1" <?php echo ($wo['config']['password_complexity_system'] == 1) ? 'checked': '';?>>
                            <label for="chck-password_complexity_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="login_auth" class="main-label">Đăng nhập bất thường</label>
                            <br><small class="admin-info">Gửi liên kết xác nhận khi người dùng đăng nhập từ một vị trí mới.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="login_auth" value="0" />
                            <input type="checkbox" name="login_auth" id="chck-login_auth" value="1" <?php echo ($wo['config']['login_auth'] == 1) ? 'checked': '';?>>
                            <label for="chck-login_auth" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="remember_device" class="main-label">Ghi nhớ thiết bị này</label>
                            <br><small class="admin-info">Ghi nhớ thiết bị này ở trang chào mừng.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="remember_device" value="0" />
                            <input type="checkbox" name="remember_device" id="chck-remember_device" value="1" <?php echo ($wo['config']['remember_device'] == 1) ? 'checked': '';?>>
                            <label for="chck-remember_device" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="login_auth" class="main-label">Xác thực hai yếu tố</label>
                            <br><small class="admin-info">Gửi mã xác nhận tới email hoặc SMS khi người dùng đăng nhập.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="two_factor" value="0" />
                            <input type="checkbox" name="two_factor" id="chck-two_factor" value="1" <?php echo ($wo['config']['two_factor'] == 1) ? 'checked': '';?>>
                            <label for="chck-two_factor" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <label for="defualtLang">Phương pháp xác thực hai yếu tố</label>
                        <br><small class="admin-info">Chọn hệ thống mà 2FA sẽ sử dụng.</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="two_factor_type" name="two_factor_type">
                              <option value="email" <?php echo ($wo['config']['two_factor_type'] == 'email') ? 'selected': '';?>>Địa chỉ email</option>
                              <option value="phone" <?php echo ($wo['config']['two_factor_type'] == 'phone') ? 'selected': '';?>>SMS / Số điện thoại</option>
                              <option value="both" <?php echo ($wo['config']['two_factor_type'] == 'both') ? 'selected': '';?>>Cả hai cùng nhau</option>
                            </select>
                        </div>
                        <hr>
                        <div class="float-left">
                            <label for="google_authenticator" class="main-label">Cài đặt Google Authenticator</label>
                            <br><small class="admin-info">Mã Google Authenticator khi người dùng đăng nhập.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="google_authenticator" value="0" />
                            <input type="checkbox" name="google_authenticator" id="chck-google_authenticator" value="1" <?php echo ($wo['config']['google_authenticator'] == '1') ? 'checked': '';?>>
                            <label for="chck-google_authenticator" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="authy_settings" class="main-label">Cài đặt xác thực</label>
                            <br><small class="admin-info">Mã xác thực khi người dùng đăng nhập.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="authy_settings" value="0" />
                            <input type="checkbox" name="authy_settings" id="chck-authy_settings" value="1" <?php echo ($wo['config']['authy_settings'] == '1') ? 'checked': '';?>>
                            <label for="chck-authy_settings" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Mã thông báo xác thực</label>
                                <input type="text" id="authy_token" name="authy_token" class="form-control" value="<?php echo $wo['config']['authy_token'] ?>">
                                <small class="admin-info">Mã thông báo xác thực từ tài khoản twilio của bạn</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="emailValidation" class="main-label">Xác thực tài khoản</label>
                            <br><small class="admin-info">Gửi liên kết kích hoạt sau khi đăng ký.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="emailValidation" value="0" />
                            <input type="checkbox" name="emailValidation" id="chck-emailValidation" value="1" <?php echo ($wo['config']['emailValidation'] == 1) ? 'checked': '';?>>
                            <label for="chck-emailValidation" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <label for="defualtLang" >Phương pháp xác thực tài khoản</label>
                        <br><small class="admin-info">Chọn loại xác thực, qua SMS hoặc E-mail, nếu bạn chọn SMS, <br> hãy đảm bảo rằng bạn đã cấu hình SMS.</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="sms_or_email" name="sms_or_email">
                                <option value="mail" <?php echo ($wo['config']['sms_or_email'] == 'mail') ? 'selected': '';?>>Địa chỉ email</option>
                                <option value="sms" <?php echo ($wo['config']['sms_or_email'] == 'sms') ? 'selected': '';?>>SMS / Số điện thoại</option>
                            </select>
                        </div>
                        <hr>
                        <div class="float-left">
                            <label for="reCaptcha" class="main-label">reCaptcha</label>
                            <br><small class="admin-info">Bật reCaptcha để ngăn chặn thư rác.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="reCaptcha" value="0" />
                            <input type="checkbox" name="reCaptcha" id="chck-reCaptcha" value="1" <?php echo ($wo['config']['reCaptcha'] == 1) ? 'checked': '';?>>
                            <label for="chck-reCaptcha" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa Recaptcha</label>
                                <input type="text" id="reCaptchaKey" name="reCaptchaKey" class="form-control" value="<?php echo $wo['config']['reCaptchaKey']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa bí mật Recaptcha</label>
                                <input type="text" id="recaptcha_secret_key" name="recaptcha_secret_key" class="form-control" value="<?php echo $wo['config']['recaptcha_secret_key']?>">
                            </div>
                        </div>
                        <hr>
                        <div class="float-left">
                            <label for="reCaptcha" class="main-label">Ngăn chặn các nỗ lực đăng nhập không hợp lệ</label>
                            <br><small class="admin-info">Bật tính năng này để theo dõi và ngăn chặn các cuộc tấn công bằng vũ lực.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="prevent_system" value="0" />
                            <input type="checkbox" name="prevent_system" id="chck-prevent_system" value="1" <?php echo ($wo['config']['prevent_system'] == 1) ? 'checked': '';?>>
                            <label for="chck-prevent_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Giới hạn đăng nhập</label>
                                <input type="text" id="bad_login_limit" name="bad_login_limit" class="form-control" value="<?php echo $wo['config']['bad_login_limit']?>">
                                <small class="admin-info">Người dùng có thể thử đăng nhập bao nhiêu lần trước khi bị khóa?</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Thời gian khóa (tính bằng phút)</label>
                                <input type="text" id="lock_time" name="lock_time" class="form-control" value="<?php echo $wo['config']['lock_time']?>">
                                <small class="admin-info">Người dùng phải bị khóa trong bao lâu?</small>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <label for="user_limit" class="main-label">Giới hạn đăng ký</label>
                            <small class="admin-info">Người dùng có thể tạo bao nhiêu tài khoản mỗi giờ?</small>
                            <div class="form-line">
                                <input type="text" id="user_limit" name="user_limit" class="form-control" value="<?php echo $wo['config']['user_limit']?>">
                                
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="float-left">
                            <label for="reserved_usernames_system" class="main-label">Tên người dùng được bảo lưu Hệ thống</label>
                            <br><small class="admin-info">Tên người dùng được bảo lưu Hệ thống</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="reserved_usernames_system" value="0" />
                            <input type="checkbox" name="reserved_usernames_system" id="chck-reserved_usernames_system" value="1" <?php echo ($wo['config']['reserved_usernames_system'] == '1') ? 'checked': '';?>>
                            <label for="chck-reserved_usernames_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên người dùng đã được đặt trước</label>
                                <textarea name="reserved_usernames" class="form-control"><?php echo ($wo['config']['reserved_usernames']);?></textarea>
                                <small class="admin-info">Tên người dùng đã được đặt trước</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="disable_start_up" class="main-label">Vô hiệu hóa trang bắt đầu</label>
                            <br><small class="admin-info">Vô hiệu hóa trang khởi động</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="disable_start_up" value="0" />
                            <input type="checkbox" name="disable_start_up" id="chck-disable_start_up" value="1" <?php echo ($wo['config']['disable_start_up'] == '1') ? 'checked': '';?>>
                            <label for="chck-disable_start_up" class="check-trail"><span class="check-handler"></span></label>
                        </div>

                        <!-- <div class="user-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt thông báo</h6>
                    <form class="notifications-settings" method="POST">
                        <div class="float-left">
                            <label for="emailNotification" class="main-label">Thông báo qua email </label>
                            <br><small class="admin-info">Gửi thông báo qua email cho người dùng sau khi nhận được thông báo từ trang web.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="emailNotification" value="0" />
                            <input type="checkbox" name="emailNotification" id="chck-emailNotification" value="1" <?php echo ($wo['config']['emailNotification'] == 1) ? 'checked': '';?>>
                            <label for="chck-emailNotification" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="profileVisit" class="main-label">Thông báo truy cập hồ sơ</label>
                            <br><small class="admin-info">Gửi thông báo cho người dùng khi có người truy cập trang cá nhân của họ. <br>Lưu ý rằng tính năng này yêu cầu người dùng phải trở thành thành viên Pro nếu bạn bật Hệ thống Pro.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="profileVisit" value="0" />
                            <input type="checkbox" name="profileVisit" id="chck-profileVisit" value="1" <?php echo ($wo['config']['profileVisit'] == 1) ? 'checked': '';?>>
                            <label for="chck-profileVisit" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="notify_new_post" class="main-label">Thông báo về bài đăng mới</label>
                            <br><small class="admin-info">Gửi thông báo cho người theo dõi khi người dùng tạo bài đăng mới.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="notify_new_post" value="0" />
                            <input type="checkbox" name="notify_new_post" id="chck-notify_new_post" value="1" <?php echo ($wo['config']['notify_new_post'] == 1) ? 'checked': '';?>>
                            <label for="chck-notify_new_post" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>

                        <!--  <div class="notifications-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>"><!-- 
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
            
            
        </div> 
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number] , textarea').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});

</script>