<div class="container-fluid">
    <div>
        <h3>Tạo trường tùy chỉnh mới</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Người dùng</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Tạo trường tùy chỉnh mới</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tạo trường tùy chỉnh mới</h6>
                    <div class="alert alert-info">Sử dụng để dịch dữ liệu trường. Ví dụ: </div>
                    <div class="add-settings-alert"></div>
                    <form class="add-settings" method="POST">
                        <label for="type">Loại trường</label>
                        <select class="form-control show-tick chosen-select" id="type" name="type">
                          <option value="textbox">Hộp văn bản</option>
               	          <option value="textarea">Vùng văn bản</option>
               	          <option value="selectbox">Chọn hộp</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên trường</label>
                                <input type="text" id="name" name="name" class="form-control">
                            </div>
                        </div>
                       
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Chiều dài trường</label>
                                <input type="text" id="length" name="length" class="form-control" value="32">
                                 <small class="admin-info">Giá trị mặc định là 32 và giá trị tối đa là 1000</small>
                            </div>
                        </div>
                         <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Mô tả trường</label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="3"></textarea>
                                <small class="admin-info">Mô tả sẽ hiển thị bên dưới trường.</small>
                            </div>
                        </div>
                        <label for="placement">Vị trí trường</label>
                        <select class="form-control show-tick " id="placement" name="placement">
                         <option value="general">Cài đặt chung</option>
		                 <option value="profile">Cài đặt hồ sơ</option>
		                 <option value="social">Liên kết xã hội</option>
		                 <option value="none">Không hiển thị trường trong trang cài đặt</option>
                        </select>
                        <small class="admin-info">Bạn muốn hiển thị trường này ở đâu?</small>
                        <div class="clearfix"></div>
                        <br>
                        <label for="registration_page">Hiển thị trên trang đăng ký</label>
                        <select class="form-control show-tick" id="registration_page" name="registration_page">
                         		<option value="0" selected>Không</option>
                 				<option value="1">Có</option>
                        </select>
                        <small class="admin-info">Bạn có muốn trường này hiển thị trên trang đăng ký không?</small>
                        <div class="clearfix"></div>
                        <br>
                        <label for="profile_page">Hiển thị trên trang hồ sơ người dùng</label>
                        <select class="form-control show-tick" id="profile_page" name="profile_page">
                         		<option value="0" selected>Không</option>
                 				<option value="1">Có</option>
                        </select>
                        <div class="clearfix"></div>
                        <br><br>
                        <div class="form-group form-float options" style="display:none">
                            <div class="form-line">
                                <label class="form-label">Chọn Tùy chọn Trường</label>
                                <textarea name="options" id="options" class="form-control" cols="30" rows="3"></textarea>
                                <small class="admin-info">Một tùy chọn trên mỗi dòng</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Tạo</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
	$('.chosen-select').on('change', function(evt, params) {
       var selectedValue = $(this).val();
       if (selectedValue == 'selectbox') {
       	  $('.options').fadeIn(200);
       } else {
       	  $('.options').fadeOut(200);
       }
       setTimeout(function () {
                      $(".content").getNiceScroll().resize()
                    }, 500);
   });
});

$(function() {
    var form_add_settings = $('form.add-settings');
    form_add_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_field',
        beforeSend: function() {
            form_add_settings.find('.waves-effect').text('Vui lòng chờ...');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.add-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Field added successfully</div>');
                setTimeout(function () {
		            window.location.href = '<?php echo Wo_LoadAdminLinkSettings('manage-profile-fields'); ?>';
		        }, 1000);
            } else if (data.status == 400) {
                $('.add-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
                setTimeout(function () {
                    $('.add-settings-alert').empty();
                }, 3000);
	        }
	        form_add_settings.find('.waves-effect').text('Create');
        }
    });
});
</script>